<?php
			$optionsArray = array( 'welcome' => array( 'welcomeItems' => array( 'collapse_button' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_uom_type',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_uom',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_sale_terms',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_payment_terms',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_pallet_type',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_address_type',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_country',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_currency',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_province',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_currency_daily_rate',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_invoices',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_invoice_payments',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_documents',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_equipment',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_equipment_assignment',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_equipment_type',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_lane',
'page' => 'list' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_order_assesorial',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_order_items',
'page' => 'list' ),
'welcome_item19' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_order_status',
'page' => 'list' ),
'welcome_item20' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_orders',
'page' => 'list' ),
'welcome_item21' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tb_activities_type',
'page' => 'list' ),
'welcome_item22' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tb_contacts_emails',
'page' => 'list' ),
'welcome_item23' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tb_contacts_phones',
'page' => 'list' ),
'welcome_item24' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tb_lead_source',
'page' => 'list' ),
'welcome_item25' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_company',
'page' => 'list' ),
'welcome_item26' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_credit_approval_Status',
'page' => 'list' ),
'welcome_item27' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_address',
'page' => 'list' ),
'welcome_item28' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tb_contacts',
'page' => 'list' ),
'welcome_item29' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_city',
'page' => 'list' ),
'welcome_item30' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_county',
'page' => 'list' ),
'welcome_item31' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'targettransportation104_v1_audit',
'page' => 'list' ),
'welcome_item32' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_company_equipment',
'page' => 'list' ),
'welcome_item33' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_company_areas',
'page' => 'list' ),
'welcome_item34' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_uomWeight',
'page' => 'list' ),
'welcome_item35' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_uomHandling',
'page' => 'list' ),
'welcome_item36' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_uomPackaging',
'page' => 'list' ),
'welcome_item37' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_rfqs',
'page' => 'list' ),
'welcome_item38' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_rfq_items',
'page' => 'list' ),
'welcome_item39' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_rfq_assesorial',
'page' => 'list' ),
'welcome_item40' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_address1',
'page' => 'list' ),
'welcome_item41' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_rfq_carrier_quote',
'page' => 'list' ),
'welcome_item42' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_rfq_status',
'page' => 'list' ),
'welcome_item43' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'vw_company_addressbook',
'page' => 'list' ),
'welcome_item44' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'vw_contacts',
'page' => 'list' ),
'welcome_group' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item45' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'forms',
'page' => 'list' ),
'welcome_item46' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'formoptions',
'page' => 'edit' ),
'welcome_item47' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'test',
'page' => 'list' ) ) ),
'welcome_item48' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'vw_rfqs_pdf',
'page' => 'list' ),
'welcome_item49' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'tbl_uomDim',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'menu',
'logo' ),
'above-grid' => array(  ),
'grid' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32',
'welcome_item33',
'welcome_item34',
'welcome_item35',
'welcome_item36',
'welcome_item37',
'welcome_item38',
'welcome_item39',
'welcome_item40',
'welcome_item41',
'welcome_item42',
'welcome_item43',
'welcome_item44',
'welcome_group',
'welcome_item48',
'welcome_item49' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'menu' => 'left',
'logo' => 'left',
'welcome_item' => 'grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid',
'welcome_item3' => 'grid',
'welcome_item4' => 'grid',
'welcome_item5' => 'grid',
'welcome_item6' => 'grid',
'welcome_item7' => 'grid',
'welcome_item8' => 'grid',
'welcome_item9' => 'grid',
'welcome_item10' => 'grid',
'welcome_item11' => 'grid',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item14' => 'grid',
'welcome_item15' => 'grid',
'welcome_item16' => 'grid',
'welcome_item17' => 'grid',
'welcome_item18' => 'grid',
'welcome_item19' => 'grid',
'welcome_item20' => 'grid',
'welcome_item21' => 'grid',
'welcome_item22' => 'grid',
'welcome_item23' => 'grid',
'welcome_item24' => 'grid',
'welcome_item25' => 'grid',
'welcome_item26' => 'grid',
'welcome_item27' => 'grid',
'welcome_item28' => 'grid',
'welcome_item29' => 'grid',
'welcome_item30' => 'grid',
'welcome_item31' => 'grid',
'welcome_item32' => 'grid',
'welcome_item33' => 'grid',
'welcome_item34' => 'grid',
'welcome_item35' => 'grid',
'welcome_item36' => 'grid',
'welcome_item37' => 'grid',
'welcome_item38' => 'grid',
'welcome_item39' => 'grid',
'welcome_item40' => 'grid',
'welcome_item41' => 'grid',
'welcome_item42' => 'grid',
'welcome_item43' => 'grid',
'welcome_item44' => 'grid',
'welcome_group' => 'grid',
'welcome_item48' => 'grid',
'welcome_item49' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'welcome_item' => array( 'welcome_item44',
'welcome_item43',
'welcome_item42',
'welcome_item41',
'welcome_item40',
'welcome_item39',
'welcome_item38',
'welcome_item37',
'welcome_item36',
'welcome_item35',
'welcome_item34',
'welcome_item33',
'welcome_item32',
'welcome_item31',
'welcome_item30',
'welcome_item29',
'welcome_item28',
'welcome_item27',
'welcome_item26',
'welcome_item25',
'welcome_item24',
'welcome_item23',
'welcome_item22',
'welcome_item21',
'welcome_item20',
'welcome_item19',
'welcome_item18',
'welcome_item17',
'welcome_item16',
'welcome_item15',
'welcome_item14',
'welcome_item13',
'welcome_item12',
'welcome_item11',
'welcome_item10',
'welcome_item9',
'welcome_item8',
'welcome_item7',
'welcome_item6',
'welcome_item5',
'welcome_item4',
'welcome_item3',
'welcome_item2',
'welcome_item1',
'welcome_item',
'welcome_item45',
'welcome_item46',
'welcome_item47',
'welcome_item48',
'welcome_item49' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'menu' => array( 'menu' ),
'logo' => array( 'logo' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'collapse_button' => array( 'collapse_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'welcome_group' => array( 'welcome_group' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'menu-topbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c0' => array( 'model' => 'c0',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32',
'welcome_item33',
'welcome_item34',
'welcome_item35',
'welcome_item36',
'welcome_item37',
'welcome_item38',
'welcome_item39',
'welcome_item40',
'welcome_item41',
'welcome_item42',
'welcome_item43',
'welcome_item44' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'welcome_group' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'welcome_item48',
'welcome_item49' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'welcome_item44' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vw_contacts',
'linkPage' => 'list',
'linkText' => array( 'table' => 'vw_contacts',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item43' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vw_company_addressbook',
'linkPage' => 'list',
'linkText' => array( 'table' => 'vw_company_addressbook',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item42' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_rfq_status',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_rfq_status',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item41' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_rfq_carrier_quote',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_rfq_carrier_quote',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item40' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_address1',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_address1',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item39' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_rfq_assesorial',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_rfq_assesorial',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item38' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_rfq_items',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_rfq_items',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item37' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_rfqs',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_rfqs',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item36' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_uomPackaging',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_uomPackaging',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item35' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_uomHandling',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_uomHandling',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item34' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_uomWeight',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_uomWeight',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item33' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_company_areas',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_company_areas',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item32' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_company_equipment',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_company_equipment',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item31' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'targettransportation104_v1_audit',
'linkPage' => 'list',
'linkText' => array( 'table' => 'targettransportation104_v1_audit',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item30' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_county',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_county',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item29' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_city',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_city',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item28' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tb_contacts',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tb_contacts',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item27' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_address',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_address',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item26' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_credit_approval_Status',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_credit_approval_Status',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item25' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_company',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_company',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item24' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tb_lead_source',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tb_lead_source',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item23' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tb_contacts_phones',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tb_contacts_phones',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item22' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tb_contacts_emails',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tb_contacts_emails',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item21' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tb_activities_type',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tb_activities_type',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item20' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_orders',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_orders',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item19' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_order_status',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_order_status',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_order_items',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_order_items',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_order_assesorial',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_order_assesorial',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_lane',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_lane',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_equipment_type',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_equipment_type',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_equipment_assignment',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_equipment_assignment',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_equipment',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_equipment',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_documents',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_documents',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_invoice_payments',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_invoice_payments',
'type' => 6 ),
'linkType' => 0 ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'menu' => array( 'type' => 'menu' ),
'logo' => array( 'type' => 'logo' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_invoices',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_invoices',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_currency_daily_rate',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_currency_daily_rate',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_province',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_province',
'type' => 6 ),
'linkType' => 0 ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_currency',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_currency',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_country',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_country',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'briefcase' ),
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_address_type',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_address_type',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_pallet_type',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_pallet_type',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'linkComments' => array( 'text' => 'Tbl Pallet Type description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_payment_terms',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_payment_terms',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'linkComments' => array( 'text' => 'Tbl Payment Terms description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_sale_terms',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_sale_terms',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'calendar' ),
'linkComments' => array( 'text' => 'Tbl Sale Terms description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_uom',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_uom',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tree-conifer' ),
'linkComments' => array( 'text' => 'Tbl Uom description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_uom_type',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_uom_type',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'leaf' ),
'linkComments' => array( 'text' => 'Tbl Uom Type description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_group' => array( 'type' => 'welcome_group',
'linkText' => array( 'text' => 'PDFForms',
'type' => 0 ),
'items' => array( 'welcome_item45',
'welcome_item46',
'welcome_item47' ) ),
'welcome_item45' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forms',
'linkPage' => 'list',
'linkText' => array( 'table' => 'forms',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tree-conifer' ),
'linkComments' => array( 'text' => 'Forms description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item46' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'formoptions',
'linkPage' => 'edit',
'linkText' => array( 'table' => 'formoptions',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'barcode' ),
'linkComments' => array( 'text' => 'Formoptions description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item47' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'test',
'linkPage' => 'list',
'linkText' => array( 'table' => 'test',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'linkComments' => array( 'text' => 'Test description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item48' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'vw_rfqs_pdf',
'linkPage' => 'list',
'linkText' => array( 'table' => 'vw_rfqs_pdf',
'type' => 6 ),
'background' => '#1E90FF',
'linkType' => 0 ),
'welcome_item49' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tbl_uomDim',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tbl_uomDim',
'type' => 6 ),
'background' => '#9ACD32',
'linkType' => 0 ) ),
'dbProps' => array(  ),
'version' => 7 );
		?>