<?php
			$optionsArray = array( 'totals' => array( 'ID' => array( 'totalsType' => '' ),
'CompanyID' => array( 'totalsType' => '' ),
'AddressID' => array( 'totalsType' => '' ),
'Login' => array( 'totalsType' => '' ),
'Password' => array( 'totalsType' => '' ),
'PasswordHint' => array( 'totalsType' => '' ),
'Name' => array( 'totalsType' => '' ),
'Email' => array( 'totalsType' => '' ),
'PrimaryPhone' => array( 'totalsType' => '' ),
'PrimaryCell' => array( 'totalsType' => '' ),
'Active' => array( 'totalsType' => '' ),
'TimeStamp' => array( 'totalsType' => '' ),
'reset_token' => array( 'totalsType' => '' ),
'reset_date' => array( 'totalsType' => '' ),
'two_factor' => array( 'totalsType' => '' ),
'totp_secret' => array( 'totalsType' => '' ),
'two_factor1' => array( 'totalsType' => '' ),
'totp_secret1' => array( 'totalsType' => '' ),
'Picture' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'CompanyID',
'AddressID',
'Login',
'PasswordHint',
'Name',
'Email',
'PrimaryPhone',
'PrimaryCell',
'Picture' ),
'exportFields' => array( 'CompanyID',
'AddressID',
'Login',
'PasswordHint',
'Name',
'Email',
'PrimaryPhone',
'PrimaryCell',
'Picture' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CompanyID' => array( 'export_field1' ),
'AddressID' => array( 'export_field2' ),
'Login' => array( 'export_field3' ),
'PasswordHint' => array( 'export_field5' ),
'Name' => array( 'export_field6' ),
'Email' => array( 'export_field7' ),
'PrimaryPhone' => array( 'export_field8' ),
'PrimaryCell' => array( 'export_field9' ),
'Picture' => array( 'export_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'CompanyID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'AddressID',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Login',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'PasswordHint',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Name',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Email',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'PrimaryPhone',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'PrimaryCell',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'Picture',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 7,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>