<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 2 ),
'details' => array( 'tbl_order_status' => array( 'displayPreview' => 2,
'previewPageId' => '',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => null,
'showProceedLink' => null,
'printDetails' => false ),
'tbl_order_items' => array( 'displayPreview' => 2,
'previewPageId' => '',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => null,
'showProceedLink' => null,
'printDetails' => false ),
'tbl_order_assesorial' => array( 'displayPreview' => 2,
'previewPageId' => '',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => null,
'showProceedLink' => null,
'printDetails' => false ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'ID' => array( 'totalsType' => '' ),
'companyID' => array( 'totalsType' => '' ),
'OrderStatusID' => array( 'totalsType' => '' ),
'Inbound' => array( 'totalsType' => '' ),
'PONumber' => array( 'totalsType' => '' ),
'BOLNumber' => array( 'totalsType' => '' ),
'ShipperID' => array( 'totalsType' => '' ),
'ShipperReferenceNo' => array( 'totalsType' => '' ),
'ShipperName' => array( 'totalsType' => '' ),
'ShipperAddress' => array( 'totalsType' => '' ),
'ShipperAddress1' => array( 'totalsType' => '' ),
'ShipperAddress2' => array( 'totalsType' => '' ),
'ShipperCity' => array( 'totalsType' => '' ),
'ShipperProvinceID' => array( 'totalsType' => '' ),
'ShipperCountryID' => array( 'totalsType' => '' ),
'ShipperCountyName' => array( 'totalsType' => '' ),
'ShipperPostal' => array( 'totalsType' => '' ),
'ShipperLongitude' => array( 'totalsType' => '' ),
'ShipperLatitude' => array( 'totalsType' => '' ),
'ShipperContactID' => array( 'totalsType' => '' ),
'ShipperContactDetails' => array( 'totalsType' => '' ),
'ShipperContactName' => array( 'totalsType' => '' ),
'ShipperContactTel' => array( 'totalsType' => '' ),
'ShipperContactFax' => array( 'totalsType' => '' ),
'ShipperContactEmail' => array( 'totalsType' => '' ),
'ShipperHoursOpen' => array( 'totalsType' => '' ),
'ShipperHoursClose' => array( 'totalsType' => '' ),
'ShipperInstructions' => array( 'totalsType' => '' ),
'ShipperDirections' => array( 'totalsType' => '' ),
'ConsigneeID' => array( 'totalsType' => '' ),
'ConsigneeReferenceNo' => array( 'totalsType' => '' ),
'ConsigneeName' => array( 'totalsType' => '' ),
'ConsigneeAddress' => array( 'totalsType' => '' ),
'ConsigneeAddress1' => array( 'totalsType' => '' ),
'ConsigneeAddress2' => array( 'totalsType' => '' ),
'ConsigneeCity' => array( 'totalsType' => '' ),
'ConsigneeProvinceID' => array( 'totalsType' => '' ),
'ConsigneeCountryID' => array( 'totalsType' => '' ),
'ConsigneeCountyName' => array( 'totalsType' => '' ),
'ConsigneePostal' => array( 'totalsType' => '' ),
'ConsigneeLongitude' => array( 'totalsType' => '' ),
'ConsigneeLatitude' => array( 'totalsType' => '' ),
'ConsigneeContactID' => array( 'totalsType' => '' ),
'ConsigneeContactDetails' => array( 'totalsType' => '' ),
'ConsigneeContactName' => array( 'totalsType' => '' ),
'ConsigneeContactTel' => array( 'totalsType' => '' ),
'ConsigneeContactFax' => array( 'totalsType' => '' ),
'ConsigneeContactEmail' => array( 'totalsType' => '' ),
'ConsigneeHoursOpen' => array( 'totalsType' => '' ),
'ConsigneeHoursClose' => array( 'totalsType' => '' ),
'ConsigneeInstructions' => array( 'totalsType' => '' ),
'ConsigneeDirections' => array( 'totalsType' => '' ),
'CarrierID' => array( 'totalsType' => '' ),
'CarrierReferenceNo' => array( 'totalsType' => '' ),
'CarrierName' => array( 'totalsType' => '' ),
'CarrierContactID' => array( 'totalsType' => '' ),
'CarrierContactDetails' => array( 'totalsType' => '' ),
'CarrierContactName' => array( 'totalsType' => '' ),
'CarrierContactTel' => array( 'totalsType' => '' ),
'CarrierContactFax' => array( 'totalsType' => '' ),
'CarrierContactEmail' => array( 'totalsType' => '' ),
'CarrierDriver' => array( 'totalsType' => '' ),
'CustomsBrokerID' => array( 'totalsType' => '' ),
'CustomsBrokerName' => array( 'totalsType' => '' ),
'CustomsContactID' => array( 'totalsType' => '' ),
'CustomsBrokerContactDetails' => array( 'totalsType' => '' ),
'CustomsBrokerContactName' => array( 'totalsType' => '' ),
'CustomsBrokerContactTel' => array( 'totalsType' => '' ),
'CustomsBrokerContactFax' => array( 'totalsType' => '' ),
'CustomsBrokerContactEmail' => array( 'totalsType' => '' ),
'PickupDateExpected' => array( 'totalsType' => '' ),
'PickupDateActual' => array( 'totalsType' => '' ),
'DeliveryDateExpected' => array( 'totalsType' => '' ),
'DeliveryDateActual' => array( 'totalsType' => '' ),
'Delivered' => array( 'totalsType' => '' ),
'POD' => array( 'totalsType' => '' ),
'PaymentTerms' => array( 'totalsType' => '' ),
'EquipmentType' => array( 'totalsType' => '' ),
'Routing' => array( 'totalsType' => '' ),
'Instructions' => array( 'totalsType' => '' ),
'Price' => array( 'totalsType' => '' ),
'Invoiced' => array( 'totalsType' => '' ),
'InvoiceID' => array( 'totalsType' => '' ),
'Paid' => array( 'totalsType' => '' ),
'Cost' => array( 'totalsType' => '' ),
'Created' => array( 'totalsType' => '' ),
'OrderNumber' => array( 'totalsType' => '' ),
'BillToPartyID' => array( 'totalsType' => '' ),
'BillToPartyReferenceNo' => array( 'totalsType' => '' ),
'BillToPartyName' => array( 'totalsType' => '' ),
'BillToAddress' => array( 'totalsType' => '' ),
'BillToPartyAddress1' => array( 'totalsType' => '' ),
'BillToPartyAddress2' => array( 'totalsType' => '' ),
'BillToPartyCity' => array( 'totalsType' => '' ),
'BillToPartyProvinceID' => array( 'totalsType' => '' ),
'BillToPartyCountryID' => array( 'totalsType' => '' ),
'BillToPartyPostal' => array( 'totalsType' => '' ),
'BillToContactID' => array( 'totalsType' => '' ),
'BillToContactDetails' => array( 'totalsType' => '' ),
'BillToPartyContactName' => array( 'totalsType' => '' ),
'BillToPartyContactTel' => array( 'totalsType' => '' ),
'BillToPartyContactFax' => array( 'totalsType' => '' ),
'BillToPartyContactEmail' => array( 'totalsType' => '' ),
'Terms' => array( 'totalsType' => '' ),
'QuotationNumber' => array( 'totalsType' => '' ),
'Modified' => array( 'totalsType' => '' ),
'ShipperRegionID' => array( 'totalsType' => '' ),
'ConsigneeRegionID' => array( 'totalsType' => '' ),
'TrailerID' => array( 'totalsType' => '' ),
'Status' => array( 'totalsType' => '' ),
'NewOrder' => array( 'totalsType' => '' ),
'PeriodStartDate' => array( 'totalsType' => '' ),
'PeriodEndDate' => array( 'totalsType' => '' ),
'Frequency' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'companyID',
'Inbound',
'PONumber',
'BOLNumber',
'ShipperID',
'ShipperCity',
'ConsigneeID',
'ConsigneeCity',
'CarrierID',
'PickupDateExpected',
'DeliveryDateExpected',
'PickupDateActual',
'DeliveryDateActual',
'ShipperContactID',
'ConsigneeContactID',
'CarrierContactID',
'CustomsContactID',
'BillToContactID',
'ShipperInstructions',
'ConsigneeInstructions',
'ShipperHoursOpen',
'ShipperHoursClose',
'ShipperDirections',
'ConsigneeHoursOpen',
'ConsigneeHoursClose',
'ConsigneeDirections',
'ShipperAddress',
'ShipperContactDetails',
'ConsigneeAddress',
'ConsigneeContactDetails',
'CarrierContactDetails',
'CustomsBrokerContactDetails',
'BillToAddress',
'BillToContactDetails' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'BOLNumber',
'BillToContactDetails',
'BillToAddress',
'CustomsBrokerContactDetails',
'CarrierContactDetails',
'ConsigneeContactDetails',
'ConsigneeAddress',
'ShipperContactDetails',
'ShipperAddress',
'ConsigneeDirections',
'ConsigneeHoursClose',
'ConsigneeHoursOpen',
'ShipperDirections',
'ShipperHoursClose',
'ShipperHoursOpen',
'ConsigneeInstructions',
'ShipperInstructions',
'BillToContactID',
'CustomsContactID',
'CarrierContactID',
'ConsigneeContactID',
'ShipperContactID',
'Inbound',
'ConsigneeLatitude',
'ConsigneeLongitude',
'ConsigneeCountyName',
'ShipperLatitude',
'ShipperLongitude',
'ShipperCountyName',
'companyID',
'TrailerID',
'Terms',
'Status',
'ShipperReferenceNo',
'ShipperProvinceID',
'ShipperPostal',
'ShipperName',
'ShipperID',
'ShipperCountryID',
'ShipperContactTel',
'ShipperContactName',
'ShipperContactFax',
'ShipperContactEmail',
'ShipperCity',
'ShipperAddress2',
'ShipperAddress1',
'Routing',
'QuotationNumber',
'Price',
'PickupDateExpected',
'PickupDateActual',
'PaymentTerms',
'Paid',
'PONumber',
'POD',
'OrderStatusID',
'OrderNumber',
'Modified',
'Invoiced',
'InvoiceID',
'Instructions',
'EquipmentType',
'DeliveryDateExpected',
'DeliveryDateActual',
'Delivered',
'CustomsBrokerName',
'CustomsBrokerID',
'CustomsBrokerContactTel',
'CustomsBrokerContactName',
'CustomsBrokerContactFax',
'CustomsBrokerContactEmail',
'Cost',
'ConsigneeReferenceNo',
'ConsigneeProvinceID',
'ConsigneePostal',
'ConsigneeName',
'ConsigneeID',
'ConsigneeCountryID',
'ConsigneeContactTel',
'ConsigneeContactName',
'ConsigneeContactFax',
'ConsigneeContactEmail',
'ConsigneeCity',
'ConsigneeAddress2',
'ConsigneeAddress1',
'CarrierReferenceNo',
'CarrierName',
'CarrierID',
'CarrierDriver',
'CarrierContactTel',
'CarrierContactName',
'CarrierContactFax',
'CarrierContactEmail',
'BillToPartyReferenceNo',
'BillToPartyProvinceID',
'BillToPartyPostal',
'BillToPartyName',
'BillToPartyID',
'BillToPartyCountryID',
'BillToPartyContactTel',
'BillToPartyContactName',
'BillToPartyContactFax',
'BillToPartyContactEmail',
'BillToPartyCity',
'BillToPartyAddress2',
'BillToPartyAddress1' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'companyID' => array( 'simple_grid_field1',
'simple_grid_field31' ),
'Inbound' => array( 'simple_grid_field3',
'simple_grid_field32' ),
'PONumber' => array( 'simple_grid_field5',
'simple_grid_field34' ),
'BOLNumber' => array( 'simple_grid_field6',
'simple_grid_field35' ),
'ShipperID' => array( 'simple_grid_field7',
'simple_grid_field36' ),
'ShipperCity' => array( 'simple_grid_field12',
'simple_grid_field37' ),
'ConsigneeID' => array( 'simple_grid_field20',
'simple_grid_field38' ),
'ConsigneeCity' => array( 'simple_grid_field25',
'simple_grid_field39' ),
'CarrierID' => array( 'simple_grid_field33',
'simple_grid_field40' ),
'PickupDateExpected' => array( 'simple_grid_field48',
'simple_grid_field49' ),
'DeliveryDateExpected' => array( 'simple_grid_field50',
'simple_grid_field51' ),
'PickupDateActual' => array( 'simple_grid_field',
'simple_grid_field41' ),
'DeliveryDateActual' => array( 'simple_grid_field2',
'simple_grid_field42' ),
'ShipperContactID' => array( 'simple_grid_field4',
'simple_grid_field43' ),
'ConsigneeContactID' => array( 'simple_grid_field8',
'simple_grid_field44' ),
'CarrierContactID' => array( 'simple_grid_field9',
'simple_grid_field45' ),
'CustomsContactID' => array( 'simple_grid_field10',
'simple_grid_field46' ),
'BillToContactID' => array( 'simple_grid_field11',
'simple_grid_field47' ),
'ShipperInstructions' => array( 'simple_grid_field13',
'simple_grid_field52' ),
'ConsigneeInstructions' => array( 'simple_grid_field14',
'simple_grid_field53' ),
'ShipperHoursOpen' => array( 'simple_grid_field15',
'simple_grid_field54' ),
'ShipperHoursClose' => array( 'simple_grid_field16',
'simple_grid_field55' ),
'ShipperDirections' => array( 'simple_grid_field17',
'simple_grid_field56' ),
'ConsigneeHoursOpen' => array( 'simple_grid_field18',
'simple_grid_field57' ),
'ConsigneeHoursClose' => array( 'simple_grid_field19',
'simple_grid_field58' ),
'ConsigneeDirections' => array( 'simple_grid_field21',
'simple_grid_field59' ),
'ShipperAddress' => array( 'simple_grid_field22',
'simple_grid_field60' ),
'ShipperContactDetails' => array( 'simple_grid_field23',
'simple_grid_field61' ),
'ConsigneeAddress' => array( 'simple_grid_field24',
'simple_grid_field62' ),
'ConsigneeContactDetails' => array( 'simple_grid_field26',
'simple_grid_field63' ),
'CarrierContactDetails' => array( 'simple_grid_field27',
'simple_grid_field64' ),
'CustomsBrokerContactDetails' => array( 'simple_grid_field28',
'simple_grid_field65' ),
'BillToAddress' => array( 'simple_grid_field29',
'simple_grid_field66' ),
'BillToContactDetails' => array( 'simple_grid_field30',
'simple_grid_field67' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field31',
'simple_grid_field1',
'simple_grid_field32',
'simple_grid_field3',
'simple_grid_field34',
'simple_grid_field5',
'simple_grid_field35',
'simple_grid_field6',
'simple_grid_field36',
'simple_grid_field7',
'simple_grid_field37',
'simple_grid_field12',
'simple_grid_field38',
'simple_grid_field20',
'simple_grid_field39',
'simple_grid_field25',
'simple_grid_field40',
'simple_grid_field33',
'simple_grid_field49',
'simple_grid_field48',
'simple_grid_field51',
'simple_grid_field50',
'simple_grid_field41',
'simple_grid_field',
'simple_grid_field42',
'simple_grid_field2',
'simple_grid_field43',
'simple_grid_field4',
'simple_grid_field44',
'simple_grid_field8',
'simple_grid_field45',
'simple_grid_field9',
'simple_grid_field46',
'simple_grid_field10',
'simple_grid_field47',
'simple_grid_field11',
'simple_grid_field52',
'simple_grid_field13',
'simple_grid_field53',
'simple_grid_field14',
'simple_grid_field54',
'simple_grid_field15',
'simple_grid_field55',
'simple_grid_field16',
'simple_grid_field56',
'simple_grid_field17',
'simple_grid_field57',
'simple_grid_field18',
'simple_grid_field58',
'simple_grid_field19',
'simple_grid_field59',
'simple_grid_field21',
'simple_grid_field60',
'simple_grid_field22',
'simple_grid_field61',
'simple_grid_field23',
'simple_grid_field62',
'simple_grid_field24',
'simple_grid_field63',
'simple_grid_field26',
'simple_grid_field64',
'simple_grid_field27',
'simple_grid_field65',
'simple_grid_field28',
'simple_grid_field66',
'simple_grid_field29',
'simple_grid_field67',
'simple_grid_field30',
'grid_edit',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field31' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field30' => 'grid',
'grid_edit' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'expand_menu_button' => 2,
'breadcrumb' => 5,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'delete_selected' => array( 'delete_selected' ),
'delete' => array( 'delete' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field36',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54',
'search_panel_field56',
'search_panel_field57',
'search_panel_field59',
'search_panel_field60',
'search_panel_field62',
'search_panel_field63',
'search_panel_field66',
'search_panel_field67',
'search_panel_field68',
'search_panel_field69',
'search_panel_field70',
'search_panel_field71',
'search_panel_field72',
'search_panel_field73',
'search_panel_field74',
'search_panel_field75',
'search_panel_field76',
'search_panel_field77',
'search_panel_field78',
'search_panel_field79',
'search_panel_field80',
'search_panel_field81',
'search_panel_field82',
'search_panel_field83',
'search_panel_field85',
'search_panel_field86',
'search_panel_field87',
'search_panel_field88',
'search_panel_field89',
'search_panel_field90',
'search_panel_field91',
'search_panel_field92',
'search_panel_field93',
'search_panel_field94',
'search_panel_field35',
'search_panel_field37',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field55',
'search_panel_field58',
'search_panel_field61',
'search_panel_field64',
'search_panel_field65',
'search_panel_field84',
'search_panel_field95',
'search_panel_field96',
'search_panel_field97',
'search_panel_field98',
'search_panel_field99',
'search_panel_field100',
'search_panel_field101',
'search_panel_field102',
'search_panel_field103',
'search_panel_field104',
'search_panel_field105' ),
'logo' => array( 'logo1' ),
'print_panel' => array( 'print_panel' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field3',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field12',
'simple_grid_field20',
'simple_grid_field25',
'simple_grid_field33',
'simple_grid_field48',
'simple_grid_field50',
'simple_grid_field',
'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30' ),
'grid_field_label' => array( 'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field49',
'simple_grid_field51',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67' ),
'grid_edit' => array( 'grid_edit' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'companyID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Inbound_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'PONumber_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'BOLNumber_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperCity_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeCity_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'CarrierID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'PickupDateExpected_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'DeliveryDateExpected_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'PickupDateActual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'DeliveryDateActual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperContactID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeContactID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'CarrierContactID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'CustomsContactID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'BillToContactID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperInstructions_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeInstructions_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperHoursOpen_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperHoursClose_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperDirections_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeHoursOpen_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeHoursClose_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeDirections_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperContactDetails_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeContactDetails_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'CarrierContactDetails_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'CustomsBrokerContactDetails_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'BillToAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'BillToContactDetails_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column' ),
'items' => array( 'grid_edit' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'companyID_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Inbound_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'PONumber_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'BOLNumber_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperID_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperCity_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeID_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeCity_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'CarrierID_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'PickupDateExpected_fieldcolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'DeliveryDateExpected_fieldcolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'PickupDateActual_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'DeliveryDateActual_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperContactID_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeContactID_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'CarrierContactID_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'CustomsContactID_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'BillToContactID_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperInstructions_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeInstructions_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperHoursOpen_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperHoursClose_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperDirections_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeHoursOpen_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeHoursClose_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeDirections_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperContactDetails_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeContactDetails_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'CarrierContactDetails_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'CustomsBrokerContactDetails_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'BillToAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'BillToContactDetails_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 36,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'companyID',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'companyID',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'Inbound',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'Inbound',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'PONumber',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'PONumber',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'BOLNumber',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'BOLNumber',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'ShipperID',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'ShipperID',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'ShipperCity',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'ShipperCity',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'ConsigneeID',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'ConsigneeID',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'ConsigneeCity',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'ConsigneeCity',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'CarrierID',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'CarrierID',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'PickupDateExpected',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'PickupDateExpected',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'DeliveryDateExpected',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'DeliveryDateExpected',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'PickupDateActual',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'PickupDateActual',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'DeliveryDateActual',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'DeliveryDateActual',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'ShipperContactID',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'ShipperContactID',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'ConsigneeContactID',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'ConsigneeContactID',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'CarrierContactID',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'CarrierContactID',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'CustomsContactID',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'CustomsContactID',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'BillToContactID',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'BillToContactID',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'ShipperInstructions',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'ShipperInstructions',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'ConsigneeInstructions',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'ConsigneeInstructions',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'ShipperHoursOpen',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'ShipperHoursOpen',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'ShipperHoursClose',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'ShipperHoursClose',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'ShipperDirections',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'ShipperDirections',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'ConsigneeHoursOpen',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'ConsigneeHoursOpen',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'ConsigneeHoursClose',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'ConsigneeHoursClose',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'ConsigneeDirections',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'ConsigneeDirections',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'ShipperAddress',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'ShipperAddress',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'ShipperContactDetails',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'ShipperContactDetails',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'ConsigneeAddress',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'ConsigneeAddress',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'ConsigneeContactDetails',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'ConsigneeContactDetails',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'CarrierContactDetails',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'CarrierContactDetails',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'CustomsBrokerContactDetails',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'CustomsBrokerContactDetails',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'BillToAddress',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'BillToAddress',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'BillToContactDetails',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'BillToContactDetails',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'delete' => array( 'type' => 'delete' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field105',
'search_panel_field104',
'search_panel_field103',
'search_panel_field102',
'search_panel_field101',
'search_panel_field100',
'search_panel_field99',
'search_panel_field98',
'search_panel_field97',
'search_panel_field96',
'search_panel_field95',
'search_panel_field84',
'search_panel_field65',
'search_panel_field64',
'search_panel_field61',
'search_panel_field58',
'search_panel_field55',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field37',
'search_panel_field35',
'search_panel_field94',
'search_panel_field93',
'search_panel_field92',
'search_panel_field91',
'search_panel_field90',
'search_panel_field89',
'search_panel_field88',
'search_panel_field87',
'search_panel_field86',
'search_panel_field85',
'search_panel_field83',
'search_panel_field82',
'search_panel_field81',
'search_panel_field80',
'search_panel_field79',
'search_panel_field78',
'search_panel_field77',
'search_panel_field76',
'search_panel_field75',
'search_panel_field74',
'search_panel_field73',
'search_panel_field72',
'search_panel_field71',
'search_panel_field70',
'search_panel_field69',
'search_panel_field68',
'search_panel_field67',
'search_panel_field66',
'search_panel_field63',
'search_panel_field62',
'search_panel_field60',
'search_panel_field59',
'search_panel_field57',
'search_panel_field56',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field36',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'BOLNumber',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'BillToPartyAddress1',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'BillToPartyAddress2',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'BillToPartyCity',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'BillToPartyContactEmail',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field5' => array( 'field' => 'BillToPartyContactFax',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field6' => array( 'field' => 'BillToPartyContactName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'BillToPartyContactTel',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field8' => array( 'field' => 'BillToPartyCountryID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'BillToPartyID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field10' => array( 'field' => 'BillToPartyName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'BillToPartyPostal',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'BillToPartyProvinceID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'BillToPartyReferenceNo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field14' => array( 'field' => 'CarrierContactEmail',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'CarrierContactFax',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'CarrierContactName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'CarrierContactTel',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'CarrierDriver',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field19' => array( 'field' => 'CarrierID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field20' => array( 'field' => 'CarrierName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field21' => array( 'field' => 'CarrierReferenceNo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field22' => array( 'field' => 'ConsigneeAddress1',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'ConsigneeAddress2',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field24' => array( 'field' => 'ConsigneeCity',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field25' => array( 'field' => 'ConsigneeContactEmail',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field26' => array( 'field' => 'ConsigneeContactFax',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field27' => array( 'field' => 'ConsigneeContactName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field28' => array( 'field' => 'ConsigneeContactTel',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field29' => array( 'field' => 'ConsigneeCountryID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field30' => array( 'field' => 'ConsigneeID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field31' => array( 'field' => 'ConsigneeName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field32' => array( 'field' => 'ConsigneePostal',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field33' => array( 'field' => 'ConsigneeProvinceID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field34' => array( 'field' => 'ConsigneeReferenceNo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field36' => array( 'field' => 'Cost',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field38' => array( 'field' => 'CustomsBrokerContactEmail',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field39' => array( 'field' => 'CustomsBrokerContactFax',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field40' => array( 'field' => 'CustomsBrokerContactName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field41' => array( 'field' => 'CustomsBrokerContactTel',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field42' => array( 'field' => 'CustomsBrokerID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field43' => array( 'field' => 'CustomsBrokerName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field44' => array( 'field' => 'Delivered',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field45' => array( 'field' => 'DeliveryDateActual',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field46' => array( 'field' => 'DeliveryDateExpected',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field47' => array( 'field' => 'EquipmentType',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field51' => array( 'field' => 'Instructions',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field52' => array( 'field' => 'InvoiceID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field53' => array( 'field' => 'Invoiced',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field54' => array( 'field' => 'Modified',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field56' => array( 'field' => 'OrderNumber',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field57' => array( 'field' => 'OrderStatusID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field59' => array( 'field' => 'POD',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field60' => array( 'field' => 'PONumber',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field62' => array( 'field' => 'Paid',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field63' => array( 'field' => 'PaymentTerms',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field66' => array( 'field' => 'PickupDateActual',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field67' => array( 'field' => 'PickupDateExpected',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field68' => array( 'field' => 'Price',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field69' => array( 'field' => 'QuotationNumber',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field70' => array( 'field' => 'Routing',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field71' => array( 'field' => 'ShipperAddress1',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field72' => array( 'field' => 'ShipperAddress2',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field73' => array( 'field' => 'ShipperCity',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field74' => array( 'field' => 'ShipperContactEmail',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field75' => array( 'field' => 'ShipperContactFax',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field76' => array( 'field' => 'ShipperContactName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field77' => array( 'field' => 'ShipperContactTel',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field78' => array( 'field' => 'ShipperCountryID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field79' => array( 'field' => 'ShipperID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field80' => array( 'field' => 'ShipperName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field81' => array( 'field' => 'ShipperPostal',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field82' => array( 'field' => 'ShipperProvinceID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field83' => array( 'field' => 'ShipperReferenceNo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field85' => array( 'field' => 'Status',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field86' => array( 'field' => 'Terms',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field87' => array( 'field' => 'TrailerID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field88' => array( 'field' => 'companyID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'logo1' => array( 'type' => 'logo' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array(  ) ),
'search_panel_field89' => array( 'field' => 'ShipperCountyName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field90' => array( 'field' => 'ShipperLongitude',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field91' => array( 'field' => 'ShipperLatitude',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field92' => array( 'field' => 'ConsigneeCountyName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field93' => array( 'field' => 'ConsigneeLongitude',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field94' => array( 'field' => 'ConsigneeLatitude',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field35' => array( 'field' => 'Inbound',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'search_panel_field37' => array( 'field' => 'ShipperContactID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field48' => array( 'field' => 'ConsigneeContactID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field49' => array( 'field' => 'CarrierContactID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field50' => array( 'field' => 'CustomsContactID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field55' => array( 'field' => 'BillToContactID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field58' => array( 'field' => 'ShipperInstructions',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field61' => array( 'field' => 'ConsigneeInstructions',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field64' => array( 'field' => 'ShipperHoursOpen',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field65' => array( 'field' => 'ShipperHoursClose',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field84' => array( 'field' => 'ShipperDirections',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field95' => array( 'field' => 'ConsigneeHoursOpen',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field96' => array( 'field' => 'ConsigneeHoursClose',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field97' => array( 'field' => 'ConsigneeDirections',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field98' => array( 'field' => 'ShipperAddress',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field99' => array( 'field' => 'ShipperContactDetails',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field100' => array( 'field' => 'ConsigneeAddress',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field101' => array( 'field' => 'ConsigneeContactDetails',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field102' => array( 'field' => 'CarrierContactDetails',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field103' => array( 'field' => 'CustomsBrokerContactDetails',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field104' => array( 'field' => 'BillToAddress',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field105' => array( 'field' => 'BillToContactDetails',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field1' => array( 'field' => 'companyID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'companyID' ),
'simple_grid_field3' => array( 'field' => 'Inbound',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'Inbound' ),
'simple_grid_field5' => array( 'field' => 'PONumber',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'PONumber' ),
'simple_grid_field6' => array( 'field' => 'BOLNumber',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'BOLNumber' ),
'simple_grid_field7' => array( 'field' => 'ShipperID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'ShipperID' ),
'simple_grid_field12' => array( 'field' => 'ShipperCity',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'ShipperCity' ),
'simple_grid_field20' => array( 'field' => 'ConsigneeID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeID' ),
'simple_grid_field25' => array( 'field' => 'ConsigneeCity',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeCity' ),
'simple_grid_field33' => array( 'field' => 'CarrierID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'CarrierID' ),
'simple_grid_field48' => array( 'field' => 'PickupDateExpected',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'PickupDateExpected' ),
'simple_grid_field50' => array( 'field' => 'DeliveryDateExpected',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'DeliveryDateExpected' ),
'simple_grid_field' => array( 'field' => 'PickupDateActual',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'PickupDateActual' ),
'simple_grid_field2' => array( 'field' => 'DeliveryDateActual',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'DeliveryDateActual' ),
'simple_grid_field4' => array( 'field' => 'ShipperContactID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'ShipperContactID' ),
'simple_grid_field8' => array( 'field' => 'ConsigneeContactID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeContactID' ),
'simple_grid_field9' => array( 'field' => 'CarrierContactID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'CarrierContactID' ),
'simple_grid_field10' => array( 'field' => 'CustomsContactID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'CustomsContactID' ),
'simple_grid_field11' => array( 'field' => 'BillToContactID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'BillToContactID' ),
'simple_grid_field13' => array( 'field' => 'ShipperInstructions',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'ShipperInstructions' ),
'simple_grid_field14' => array( 'field' => 'ConsigneeInstructions',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeInstructions' ),
'simple_grid_field15' => array( 'field' => 'ShipperHoursOpen',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'ShipperHoursOpen' ),
'simple_grid_field16' => array( 'field' => 'ShipperHoursClose',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'ShipperHoursClose' ),
'simple_grid_field17' => array( 'field' => 'ShipperDirections',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'ShipperDirections' ),
'simple_grid_field18' => array( 'field' => 'ConsigneeHoursOpen',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeHoursOpen' ),
'simple_grid_field19' => array( 'field' => 'ConsigneeHoursClose',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeHoursClose' ),
'simple_grid_field21' => array( 'field' => 'ConsigneeDirections',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeDirections' ),
'simple_grid_field22' => array( 'field' => 'ShipperAddress',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'ShipperAddress' ),
'simple_grid_field23' => array( 'field' => 'ShipperContactDetails',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'ShipperContactDetails' ),
'simple_grid_field24' => array( 'field' => 'ConsigneeAddress',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeAddress' ),
'simple_grid_field26' => array( 'field' => 'ConsigneeContactDetails',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeContactDetails' ),
'simple_grid_field27' => array( 'field' => 'CarrierContactDetails',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'CarrierContactDetails' ),
'simple_grid_field28' => array( 'field' => 'CustomsBrokerContactDetails',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'CustomsBrokerContactDetails' ),
'simple_grid_field29' => array( 'field' => 'BillToAddress',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'BillToAddress' ),
'simple_grid_field30' => array( 'field' => 'BillToContactDetails',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'BillToContactDetails' ),
'grid_edit' => array( 'type' => 'grid_edit' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 7 );
		?>