<?php
			$optionsArray = array( 'details' => array( 'tbl_order_status' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'tbl_order_items' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'tbl_order_assesorial' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'ShipperName',
'BillToPartyProvinceID',
'BillToPartyCountryID',
'BillToPartyCity',
'BillToPartyAddress2',
'BillToPartyAddress1',
'BillToPartyName',
'BillToAddress',
'BillToPartyReferenceNo',
'BillToPartyID',
'ConsigneeContactEmail',
'ConsigneeContactFax',
'ConsigneeContactTel',
'ConsigneeContactName',
'ConsigneeContactDetails',
'ConsigneeContactID',
'ConsigneeDirections',
'ConsigneeInstructions',
'ConsigneeLongitude',
'ConsigneeLatitude',
'ConsigneePostal',
'ConsigneeCountyName',
'ConsigneeProvinceID',
'ConsigneeCountryID',
'ConsigneeCity',
'ConsigneeAddress2',
'ConsigneeAddress1',
'ConsigneeName',
'ConsigneeHoursClose',
'ConsigneeHoursOpen',
'ConsigneeAddress',
'ConsigneeReferenceNo',
'ConsigneeID',
'ShipperContactEmail',
'ShipperContactFax',
'ShipperContactTel',
'ShipperContactName',
'ShipperContactID',
'ShipperDirections',
'ShipperInstructions',
'ShipperLatitude',
'ShipperLongitude',
'ShipperPostal',
'ShipperCountyName',
'ShipperCountryID',
'ShipperProvinceID',
'ShipperCity',
'ShipperAddress2',
'ShipperAddress1',
'ShipperHoursOpen',
'ShipperHoursClose',
'DeliveryDateExpected',
'PickupDateExpected',
'BillToPartyContactEmail',
'BillToPartyContactFax',
'BillToPartyContactTel',
'BillToPartyContactName',
'BillToContactDetails',
'BillToContactID',
'BillToPartyPostal',
'ShipperAddress',
'ShipperReferenceNo',
'ShipperID',
'Routing',
'Instructions',
'EquipmentType',
'Terms',
'PaymentTerms',
'Inbound',
'companyID' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ShipperName' => array( 'integrated_edit_field7' ),
'BillToPartyProvinceID' => array( 'integrated_edit_field75' ),
'BillToPartyCountryID' => array( 'integrated_edit_field76' ),
'BillToPartyCity' => array( 'integrated_edit_field74' ),
'BillToPartyAddress2' => array( 'integrated_edit_field73' ),
'BillToPartyAddress1' => array( 'integrated_edit_field72' ),
'BillToPartyName' => array( 'integrated_edit_field71' ),
'BillToAddress' => array( 'integrated_edit_field53' ),
'BillToPartyReferenceNo' => array( 'integrated_edit_field70' ),
'BillToPartyID' => array( 'integrated_edit_field69' ),
'ConsigneeContactEmail' => array( 'integrated_edit_field36' ),
'ConsigneeContactFax' => array( 'integrated_edit_field35' ),
'ConsigneeContactTel' => array( 'integrated_edit_field34' ),
'ConsigneeContactName' => array( 'integrated_edit_field33' ),
'ConsigneeContactDetails' => array( 'integrated_edit_field49' ),
'ConsigneeContactID' => array( 'integrated_edit_field4' ),
'ConsigneeDirections' => array( 'integrated_edit_field45' ),
'ConsigneeInstructions' => array( 'integrated_edit_field39' ),
'ConsigneeLongitude' => array( 'integrated_edit_field31' ),
'ConsigneeLatitude' => array( 'integrated_edit_field32' ),
'ConsigneePostal' => array( 'integrated_edit_field30' ),
'ConsigneeCountyName' => array( 'integrated_edit_field29' ),
'ConsigneeProvinceID' => array( 'integrated_edit_field27' ),
'ConsigneeCountryID' => array( 'integrated_edit_field28' ),
'ConsigneeCity' => array( 'integrated_edit_field26' ),
'ConsigneeAddress2' => array( 'integrated_edit_field25' ),
'ConsigneeAddress1' => array( 'integrated_edit_field24' ),
'ConsigneeName' => array( 'integrated_edit_field23' ),
'ConsigneeHoursClose' => array( 'integrated_edit_field44' ),
'ConsigneeHoursOpen' => array( 'integrated_edit_field43' ),
'ConsigneeAddress' => array( 'integrated_edit_field48' ),
'ConsigneeReferenceNo' => array( 'integrated_edit_field22' ),
'ConsigneeID' => array( 'integrated_edit_field21' ),
'ShipperContactEmail' => array( 'integrated_edit_field20' ),
'ShipperContactFax' => array( 'integrated_edit_field19' ),
'ShipperContactTel' => array( 'integrated_edit_field18' ),
'ShipperContactName' => array( 'integrated_edit_field17' ),
'ShipperContactID' => array( 'integrated_edit_field3' ),
'ShipperDirections' => array( 'integrated_edit_field42' ),
'ShipperInstructions' => array( 'integrated_edit_field37' ),
'ShipperLatitude' => array( 'integrated_edit_field16' ),
'ShipperLongitude' => array( 'integrated_edit_field15' ),
'ShipperPostal' => array( 'integrated_edit_field14' ),
'ShipperCountyName' => array( 'integrated_edit_field13' ),
'ShipperCountryID' => array( 'integrated_edit_field12' ),
'ShipperProvinceID' => array( 'integrated_edit_field11' ),
'ShipperCity' => array( 'integrated_edit_field10' ),
'ShipperAddress2' => array( 'integrated_edit_field9' ),
'ShipperAddress1' => array( 'integrated_edit_field8' ),
'ShipperHoursOpen' => array( 'integrated_edit_field40' ),
'ShipperHoursClose' => array( 'integrated_edit_field41' ),
'DeliveryDateExpected' => array( 'integrated_edit_field54' ),
'PickupDateExpected' => array( 'integrated_edit_field52' ),
'BillToPartyContactEmail' => array( 'integrated_edit_field81' ),
'BillToPartyContactFax' => array( 'integrated_edit_field80' ),
'BillToPartyContactTel' => array( 'integrated_edit_field79' ),
'BillToPartyContactName' => array( 'integrated_edit_field78' ),
'BillToContactDetails' => array( 'integrated_edit_field56' ),
'BillToContactID' => array( 'integrated_edit_field38' ),
'BillToPartyPostal' => array( 'integrated_edit_field77' ),
'ShipperAddress' => array( 'integrated_edit_field47' ),
'ShipperReferenceNo' => array( 'integrated_edit_field6' ),
'ShipperID' => array( 'integrated_edit_field5' ),
'Routing' => array( 'integrated_edit_field60' ),
'EquipmentType' => array( 'edit_field_tooltip3',
'integrated_edit_field59',
'edit_field_label3' ),
'Terms' => array( 'edit_field_tooltip2',
'integrated_edit_field82',
'edit_field_label2' ),
'PaymentTerms' => array( 'edit_field_tooltip1',
'integrated_edit_field58',
'edit_field_label1' ),
'Inbound' => array( 'edit_field_tooltip',
'integrated_edit_field2',
'edit_field_label' ),
'Instructions' => array( 'integrated_edit_field61',
'edit_field_tooltip4',
'edit_field_label4' ),
'companyID' => array( 'integrated_edit_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'integrated_edit_field',
'tabs' ),
'section' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2',
'edit_field_label3',
'edit_field_label4',
'edit_field_tooltip4',
'integrated_edit_field2',
'integrated_edit_field58',
'integrated_edit_field82',
'integrated_edit_field59',
'integrated_edit_field61',
'edit_field_tooltip',
'edit_field_tooltip1',
'edit_field_tooltip2',
'edit_field_tooltip3' ),
'section1' => array( 'integrated_edit_field60' ),
'section2' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field47',
'section1',
'section3',
'integrated_edit_field37',
'integrated_edit_field42',
'integrated_edit_field3',
'section' ),
'section3' => array( 'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field48',
'section2',
'section4',
'integrated_edit_field39',
'integrated_edit_field45',
'integrated_edit_field4',
'integrated_edit_field49',
'section5' ),
'section7' => array( 'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20' ),
'section4' => array( 'details_preview1' ),
'section5' => array( 'details_preview' ),
'section6' => array( 'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field53',
'section6',
'integrated_edit_field38',
'integrated_edit_field56',
'section7' ),
'section8' => array( 'integrated_edit_field52',
'integrated_edit_field54' ),
'section10' => array( 'integrated_edit_field43',
'integrated_edit_field44' ),
'section9' => array( 'integrated_edit_field40',
'integrated_edit_field41' ),
'section11' => array( 'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16' ),
'section12' => array( 'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field27',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field32',
'integrated_edit_field31' ),
'section13' => array( 'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36' ),
'section14' => array( 'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field76',
'integrated_edit_field75',
'integrated_edit_field77' ),
'section15' => array( 'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'integrated_edit_field' => 'grid',
'tabs' => 'grid',
'edit_field_label' => 'section',
'edit_field_label1' => 'section',
'edit_field_label2' => 'section',
'edit_field_label3' => 'section',
'edit_field_label4' => 'section',
'edit_field_tooltip4' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field58' => 'section',
'integrated_edit_field82' => 'section',
'integrated_edit_field59' => 'section',
'integrated_edit_field61' => 'section',
'edit_field_tooltip' => 'section',
'edit_field_tooltip1' => 'section',
'edit_field_tooltip2' => 'section',
'edit_field_tooltip3' => 'section',
'integrated_edit_field60' => 'section1',
'integrated_edit_field5' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field7' => 'section2',
'integrated_edit_field47' => 'section2',
'section1' => 'section2',
'section3' => 'section2',
'integrated_edit_field37' => 'section2',
'integrated_edit_field42' => 'section2',
'integrated_edit_field3' => 'section2',
'section' => 'section2',
'integrated_edit_field21' => 'section3',
'integrated_edit_field22' => 'section3',
'integrated_edit_field48' => 'section3',
'section2' => 'section3',
'section4' => 'section3',
'integrated_edit_field39' => 'section3',
'integrated_edit_field45' => 'section3',
'integrated_edit_field4' => 'section3',
'integrated_edit_field49' => 'section3',
'section5' => 'section3',
'integrated_edit_field17' => 'section7',
'integrated_edit_field18' => 'section7',
'integrated_edit_field19' => 'section7',
'integrated_edit_field20' => 'section7',
'details_preview1' => 'section4',
'details_preview' => 'section5',
'integrated_edit_field69' => 'section6',
'integrated_edit_field70' => 'section6',
'integrated_edit_field53' => 'section6',
'section6' => 'section6',
'integrated_edit_field38' => 'section6',
'integrated_edit_field56' => 'section6',
'section7' => 'section6',
'integrated_edit_field52' => 'section8',
'integrated_edit_field54' => 'section8',
'integrated_edit_field43' => 'section10',
'integrated_edit_field44' => 'section10',
'integrated_edit_field40' => 'section9',
'integrated_edit_field41' => 'section9',
'integrated_edit_field8' => 'section11',
'integrated_edit_field9' => 'section11',
'integrated_edit_field10' => 'section11',
'integrated_edit_field11' => 'section11',
'integrated_edit_field12' => 'section11',
'integrated_edit_field13' => 'section11',
'integrated_edit_field14' => 'section11',
'integrated_edit_field15' => 'section11',
'integrated_edit_field16' => 'section11',
'integrated_edit_field23' => 'section12',
'integrated_edit_field24' => 'section12',
'integrated_edit_field25' => 'section12',
'integrated_edit_field26' => 'section12',
'integrated_edit_field28' => 'section12',
'integrated_edit_field27' => 'section12',
'integrated_edit_field29' => 'section12',
'integrated_edit_field30' => 'section12',
'integrated_edit_field32' => 'section12',
'integrated_edit_field31' => 'section12',
'integrated_edit_field33' => 'section13',
'integrated_edit_field34' => 'section13',
'integrated_edit_field35' => 'section13',
'integrated_edit_field36' => 'section13',
'integrated_edit_field71' => 'section14',
'integrated_edit_field72' => 'section14',
'integrated_edit_field73' => 'section14',
'integrated_edit_field74' => 'section14',
'integrated_edit_field76' => 'section14',
'integrated_edit_field75' => 'section14',
'integrated_edit_field77' => 'section14',
'integrated_edit_field78' => 'section15',
'integrated_edit_field79' => 'section15',
'integrated_edit_field80' => 'section15',
'integrated_edit_field81' => 'section15' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_label' => array( 'location' => 'section',
'cellId' => 'c1' ),
'edit_field_label1' => array( 'location' => 'section',
'cellId' => 'c' ),
'edit_field_label2' => array( 'location' => 'section',
'cellId' => 'c2' ),
'edit_field_label3' => array( 'location' => 'section',
'cellId' => 'c3' ),
'edit_field_label4' => array( 'location' => 'section',
'cellId' => 'c4' ),
'edit_field_tooltip4' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field58' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field82' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field59' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field61' => array( 'location' => 'section',
'cellId' => 'c9' ),
'edit_field_tooltip' => array( 'location' => 'section',
'cellId' => 'c10' ),
'edit_field_tooltip1' => array( 'location' => 'section',
'cellId' => 'c11' ),
'edit_field_tooltip2' => array( 'location' => 'section',
'cellId' => 'c12' ),
'edit_field_tooltip3' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field60' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field47' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'section1' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'section3' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field37' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field42' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field3' => array( 'location' => 'section2',
'cellId' => 'c' ),
'section' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field21' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field48' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'section2' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'section4' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field39' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field45' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field4' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field49' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'section5' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field17' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field18' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field19' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field20' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'details_preview1' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'details_preview' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field69' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field70' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field53' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'section6' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field38' => array( 'location' => 'section6',
'cellId' => 'c' ),
'integrated_edit_field56' => array( 'location' => 'section6',
'cellId' => 'c' ),
'section7' => array( 'location' => 'section6',
'cellId' => 'c' ),
'integrated_edit_field52' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field54' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field43' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field44' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field40' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field41' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field13' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field26' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field28' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field27' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field29' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field30' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field32' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field33' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'integrated_edit_field35' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'integrated_edit_field36' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'integrated_edit_field71' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field72' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field73' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field74' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field76' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field75' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field77' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field78' => array( 'location' => 'section15',
'cellId' => 'c1' ),
'integrated_edit_field79' => array( 'location' => 'section15',
'cellId' => 'c1' ),
'integrated_edit_field80' => array( 'location' => 'section15',
'cellId' => 'c1' ),
'integrated_edit_field81' => array( 'location' => 'section15',
'cellId' => 'c1' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'integrated_edit_field' => array( 'integrated_edit_field7',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field74',
'integrated_edit_field73',
'integrated_edit_field72',
'integrated_edit_field71',
'integrated_edit_field53',
'integrated_edit_field70',
'integrated_edit_field69',
'integrated_edit_field36',
'integrated_edit_field35',
'integrated_edit_field34',
'integrated_edit_field33',
'integrated_edit_field49',
'integrated_edit_field4',
'integrated_edit_field45',
'integrated_edit_field39',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field30',
'integrated_edit_field29',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field44',
'integrated_edit_field43',
'integrated_edit_field48',
'integrated_edit_field22',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field19',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field3',
'integrated_edit_field42',
'integrated_edit_field37',
'integrated_edit_field16',
'integrated_edit_field15',
'integrated_edit_field14',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field11',
'integrated_edit_field10',
'integrated_edit_field9',
'integrated_edit_field8',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field54',
'integrated_edit_field52',
'integrated_edit_field81',
'integrated_edit_field80',
'integrated_edit_field79',
'integrated_edit_field78',
'integrated_edit_field56',
'integrated_edit_field38',
'integrated_edit_field77',
'integrated_edit_field47',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field60',
'integrated_edit_field' ),
'section' => array( 'section6',
'section5',
'section4',
'section2',
'section',
'section3',
'section1',
'section7' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'details_preview' => array( 'details_preview',
'details_preview1' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'edit_field_tooltip' => array( 'edit_field_tooltip3',
'edit_field_tooltip2',
'edit_field_tooltip1',
'edit_field_tooltip',
'edit_field_tooltip4' ),
'edit_field' => array( 'integrated_edit_field61',
'integrated_edit_field59',
'integrated_edit_field82',
'integrated_edit_field58',
'integrated_edit_field2' ),
'edit_field_label' => array( 'edit_field_label4',
'edit_field_label3',
'edit_field_label2',
'edit_field_label1',
'edit_field_label' ),
'tabs' => array( 'tabs' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'Inbound_fieldblock' ),
'items' => array( 'edit_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'PaymentTerms_fieldblock' ),
'items' => array( 'edit_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field58' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'Terms_fieldblock' ),
'items' => array( 'edit_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field82' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_tooltip2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'EquipmentType_fieldblock' ),
'items' => array( 'edit_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field59' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'edit_field_tooltip3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'edit_field_label4',
'edit_field_tooltip4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field61' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 5 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field60' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field47',
'section1',
'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37',
'integrated_edit_field42',
'integrated_edit_field3',
'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field48',
'section2',
'section4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39',
'integrated_edit_field45',
'integrated_edit_field4',
'integrated_edit_field49',
'section5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field53',
'section6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38',
'integrated_edit_field56',
'section7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field52',
'integrated_edit_field54' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43',
'integrated_edit_field44' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40',
'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section11' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section12' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field27',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field32',
'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section13' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section14' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field76',
'integrated_edit_field75',
'integrated_edit_field77' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section15' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field',
'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c10' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c12' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c13' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c9',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c3',
'items' => array( 'edit_field_label' ),
'align' => 'right' ),
'c' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1' ),
'align' => 'right' ),
'c2' => array( 'model' => 'c3',
'items' => array( 'edit_field_label2' ),
'align' => 'right' ),
'c3' => array( 'model' => 'c3',
'items' => array( 'edit_field_label3' ),
'align' => 'right' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'edit_field_label4',
'edit_field_tooltip4' ),
'align' => 'right' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field58' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field82' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field59' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field61' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'edit_field_tooltip' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'edit_field_tooltip1' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'edit_field_tooltip2' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'edit_field_tooltip3' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field60' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field47',
'section1',
'section3' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37',
'integrated_edit_field42',
'integrated_edit_field3',
'section' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field48',
'section2',
'section4' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39',
'integrated_edit_field45',
'integrated_edit_field4',
'integrated_edit_field49',
'section5' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field53',
'section6' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field38',
'integrated_edit_field56',
'section7' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field52',
'integrated_edit_field54' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43',
'integrated_edit_field44' ),
'orientation' => 'horizontal' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40',
'integrated_edit_field41' ),
'orientation' => 'horizontal' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section11' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section12' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field27',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field32',
'integrated_edit_field31' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section13' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section14' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field76',
'integrated_edit_field75',
'integrated_edit_field77' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section15' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'integrated_edit_field7' => array( 'field' => 'ShipperName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field75' => array( 'field' => 'BillToPartyProvinceID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field76' => array( 'field' => 'BillToPartyCountryID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field74' => array( 'field' => 'BillToPartyCity',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field73' => array( 'field' => 'BillToPartyAddress2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field72' => array( 'field' => 'BillToPartyAddress1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field71' => array( 'field' => 'BillToPartyName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section6' => array( 'type' => 'section',
'title' => array( 'text' => 'Address Details',
'type' => 0 ),
'location' => 'section14' ),
'integrated_edit_field53' => array( 'field' => 'BillToAddress',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field70' => array( 'field' => 'BillToPartyReferenceNo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field69' => array( 'field' => 'BillToPartyID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'ConsigneeContactEmail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'ConsigneeContactFax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'ConsigneeContactTel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'ConsigneeContactName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section5' => array( 'type' => 'section',
'title' => array( 'text' => 'Contact Details',
'type' => 0 ),
'location' => 'section13',
'initiallyClosed' => true ),
'integrated_edit_field49' => array( 'field' => 'ConsigneeContactDetails',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'ConsigneeContactID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'ConsigneeDirections',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'ConsigneeInstructions',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'ConsigneeLongitude',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'ConsigneeLatitude',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'ConsigneePostal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'ConsigneeCountyName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'ConsigneeProvinceID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'ConsigneeCountryID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'ConsigneeCity',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'ConsigneeAddress2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'ConsigneeAddress1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'ConsigneeName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Address Details',
'type' => 0 ),
'location' => 'section12',
'initiallyClosed' => true ),
'integrated_edit_field44' => array( 'field' => 'ConsigneeHoursClose',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'ConsigneeHoursOpen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Hours of operation',
'type' => 0 ),
'location' => 'section10' ),
'integrated_edit_field48' => array( 'field' => 'ConsigneeAddress',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'ConsigneeReferenceNo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'ConsigneeID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'ShipperContactEmail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'ShipperContactFax',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => '' ),
'integrated_edit_field18' => array( 'field' => 'ShipperContactTel',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileControl' => 'button',
'mobileDisplay' => '' ),
'integrated_edit_field17' => array( 'field' => 'ShipperContactName',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileControl' => 'button',
'mobileDisplay' => '' ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Contact Details',
'type' => 0 ),
'location' => 'section7',
'mobileDisplay' => '',
'initiallyClosed' => true ),
'integrated_edit_field3' => array( 'field' => 'ShipperContactID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'ShipperDirections',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'ShipperInstructions',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'ShipperLatitude',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => '',
'mobileControl' => 'button' ),
'integrated_edit_field15' => array( 'field' => 'ShipperLongitude',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => '',
'mobileControl' => 'button' ),
'integrated_edit_field14' => array( 'field' => 'ShipperPostal',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => '',
'mobileControl' => 'button' ),
'integrated_edit_field13' => array( 'field' => 'ShipperCountyName',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => '',
'mobileControl' => 'button' ),
'integrated_edit_field12' => array( 'field' => 'ShipperCountryID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'ShipperProvinceID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'ShipperCity',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => '',
'mobileControl' => 'button' ),
'integrated_edit_field9' => array( 'field' => 'ShipperAddress2',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => '',
'mobileControl' => 'button' ),
'integrated_edit_field8' => array( 'field' => 'ShipperAddress1',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => '' ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Address details',
'type' => 0 ),
'location' => 'section11',
'initiallyClosed' => true ),
'integrated_edit_field40' => array( 'field' => 'ShipperHoursOpen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'logo1' => array( 'type' => 'logo' ),
'integrated_edit_field41' => array( 'field' => 'ShipperHoursClose',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Hours of Operation',
'type' => 0 ),
'location' => 'section9' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'tbl_rfq_carrier_quote',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'tbl_rfq_items',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'integrated_edit_field54' => array( 'field' => 'DeliveryDateExpected',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field52' => array( 'field' => 'PickupDateExpected',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field81' => array( 'field' => 'BillToPartyContactEmail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field80' => array( 'field' => 'BillToPartyContactFax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field79' => array( 'field' => 'BillToPartyContactTel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field78' => array( 'field' => 'BillToPartyContactName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section7' => array( 'type' => 'section',
'title' => array( 'text' => 'Contact Details',
'type' => 0 ),
'location' => 'section15',
'initiallyClosed' => true ),
'integrated_edit_field56' => array( 'field' => 'BillToContactDetails',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'BillToContactID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field77' => array( 'field' => 'BillToPartyPostal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'ShipperAddress',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => 'both' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'integrated_edit_field6' => array( 'field' => 'ShipperReferenceNo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'ShipperID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field60' => array( 'field' => 'Routing',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_field_tooltip3' => array( 'type' => 'edit_field_tooltip',
'field' => 'EquipmentType',
'separated' => true ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'Terms',
'separated' => true ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'PaymentTerms',
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'Inbound',
'separated' => true ),
'integrated_edit_field61' => array( 'field' => 'Instructions',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field59' => array( 'field' => 'EquipmentType',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field82' => array( 'field' => 'Terms',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field58' => array( 'field' => 'PaymentTerms',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field2' => array( 'field' => 'Inbound',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'edit_field_tooltip4' => array( 'type' => 'edit_field_tooltip',
'field' => 'Instructions',
'separated' => true ),
'edit_field_label4' => array( 'type' => 'edit_field_label',
'field' => 'Instructions',
'separated' => true ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'EquipmentType',
'separated' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'Terms',
'separated' => true ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'PaymentTerms',
'separated' => true ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'Inbound',
'separated' => true ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'General',
'type' => 0 ),
array( 'text' => 'References',
'type' => 0 ),
array( 'text' => 'Shipper',
'type' => 0 ),
array( 'text' => 'Consignee',
'type' => 0 ),
array( 'text' => 'Bill To',
'type' => 0 ),
array( 'text' => 'Dates',
'type' => 0 ),
array( 'text' => 'Items',
'type' => 0 ),
array( 'text' => 'Quotations',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2',
'section3',
'section6',
'section8',
'section4',
'section5' ) ),
'integrated_edit_field' => array( 'field' => 'companyID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 7 );
		?>