<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'details' => array( 'tbl_address' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tbl_documents' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tb_contacts' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tbl_company_equipment' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tbl_company_areas' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tbl_users' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ) ),
'fields' => array( 'gridFields' => array( 'PrimaryPhone',
'PrimaryFax',
'SalesRepID',
'CreditApprovalStatus',
'Insurance',
'Comments',
'ReferenceNumber',
'CustomerNumber',
'BusinessNumber',
'INCOTermsID',
'INCOTermsDescription',
'PaymentTermsID',
'CADBankInstitutionNumber',
'CADBankroutingNumber',
'CADBankAccountNumber',
'Type',
'CarrierSCAC_Number',
'CarrierDOT_Number',
'CarrierMC_Number',
'CarrierDunns_Number',
'CarrierInsuranceCargoPolicyNumber',
'CarrierInsuranceCargoAmount',
'CarrierInsuranceCargoStartDate',
'CarrierInsuranceCargoExpiryDate',
'CarrierInsuranceLiabilityPolicyNumber',
'CarrierInsuranceLiabilityAmount',
'CarrierInsuranceLiabilityStartDate',
'CarrierInsuranceLiabilityExpiryDate' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PrimaryPhone' => array( 'integrated_edit_field5' ),
'PrimaryFax' => array( 'integrated_edit_field21' ),
'SalesRepID' => array( 'integrated_edit_field6' ),
'CreditApprovalStatus' => array( 'integrated_edit_field7' ),
'Insurance' => array( 'integrated_edit_field8' ),
'Comments' => array( 'integrated_edit_field4' ),
'ReferenceNumber' => array( 'integrated_edit_field' ),
'CustomerNumber' => array( 'integrated_edit_field3' ),
'BusinessNumber' => array( 'integrated_edit_field2' ),
'INCOTermsID' => array( 'integrated_edit_field12' ),
'INCOTermsDescription' => array( 'integrated_edit_field13' ),
'PaymentTermsID' => array( 'integrated_edit_field14' ),
'CADBankInstitutionNumber' => array( 'integrated_edit_field9' ),
'CADBankroutingNumber' => array( 'integrated_edit_field10' ),
'CADBankAccountNumber' => array( 'integrated_edit_field11' ),
'Type' => array( 'integrated_edit_field1' ),
'CarrierSCAC_Number' => array( 'integrated_edit_field15' ),
'CarrierDOT_Number' => array( 'integrated_edit_field16' ),
'CarrierMC_Number' => array( 'integrated_edit_field17' ),
'CarrierDunns_Number' => array( 'integrated_edit_field18' ),
'CarrierInsuranceCargoPolicyNumber' => array( 'integrated_edit_field19' ),
'CarrierInsuranceCargoAmount' => array( 'integrated_edit_field20' ),
'CarrierInsuranceCargoStartDate' => array( 'integrated_edit_field22' ),
'CarrierInsuranceCargoExpiryDate' => array( 'integrated_edit_field23' ),
'CarrierInsuranceLiabilityPolicyNumber' => array( 'integrated_edit_field24' ),
'CarrierInsuranceLiabilityAmount' => array( 'integrated_edit_field25' ),
'CarrierInsuranceLiabilityStartDate' => array( 'integrated_edit_field26' ),
'CarrierInsuranceLiabilityExpiryDate' => array( 'integrated_edit_field27' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'section',
'section1',
'section7',
'section6',
'section9',
'section5',
'section4',
'section8',
'section2',
'section3',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27' ),
'section' => array( 'details_preview1' ),
'section1' => array( 'details_preview3' ),
'section2' => array( 'details_preview4' ),
'section10' => array( 'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field21',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field4' ),
'section11' => array( 'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field2' ),
'section12' => array( 'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14' ),
'section13' => array( 'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'section14' => array( 'details_preview' ),
'section15' => array( 'details_preview2' ),
'section3' => array( 'details_preview5' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'section' => 'grid',
'section1' => 'grid',
'section7' => 'grid',
'section6' => 'grid',
'section9' => 'grid',
'section5' => 'grid',
'section4' => 'grid',
'section8' => 'grid',
'section2' => 'grid',
'section3' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field27' => 'grid',
'details_preview1' => 'section',
'details_preview3' => 'section1',
'details_preview4' => 'section2',
'integrated_edit_field1' => 'section10',
'integrated_edit_field5' => 'section10',
'integrated_edit_field21' => 'section10',
'integrated_edit_field6' => 'section10',
'integrated_edit_field7' => 'section10',
'integrated_edit_field8' => 'section10',
'integrated_edit_field4' => 'section10',
'integrated_edit_field' => 'section11',
'integrated_edit_field3' => 'section11',
'integrated_edit_field2' => 'section11',
'integrated_edit_field12' => 'section12',
'integrated_edit_field13' => 'section12',
'integrated_edit_field14' => 'section12',
'integrated_edit_field9' => 'section13',
'integrated_edit_field10' => 'section13',
'integrated_edit_field11' => 'section13',
'details_preview' => 'section14',
'details_preview2' => 'section15',
'details_preview5' => 'section3' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'section7' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'section6' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'section9' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'section5' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'section4' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'section8' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'section2' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c' ),
'details_preview1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'details_preview3' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'details_preview4' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field1' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field13' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'details_preview' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'details_preview2' => array( 'location' => 'section15',
'cellId' => 'c1' ),
'details_preview5' => array( 'location' => 'section3',
'cellId' => 'c1' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field5',
'integrated_edit_field21',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field4',
'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field2',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field1',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'details_preview5' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'section' => array( 'section',
'section1',
'section2',
'section3',
'section4',
'section5',
'section6',
'section7',
'section8',
'section9' ),
'view_pdf' => array( 'view_pdf' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'section6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0,
1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'section7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'section9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 8 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field21',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section11' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section12' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section13' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section14' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section15' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 2,
'rowspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 2,
'rowspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'padding' => array( 'padding' => '5px' ),
'height' => '100%' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'section1' ),
'padding' => array( 'padding' => '5px' ),
'height' => '100%' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'section7' ),
'padding' => array( 'padding' => '5px' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'section6' ),
'padding' => array( 'padding' => '5px' ) ),
'c1' => array( 'model' => 'c3',
'items' => array( 'section9' ),
'padding' => array( 'padding' => '5px' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'section5' ),
'padding' => array( 'padding' => '5px' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'section4' ),
'padding' => array( 'padding' => '5px' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'section8' ),
'padding' => array( 'padding' => '5px' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'section2' ),
'padding' => array( 'padding' => '5px' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'section3' ),
'padding' => array( 'padding' => '5px' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => true,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1,
'rowspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field5',
'integrated_edit_field21',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'vertical',
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section11' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'height' => '100%' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section12' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section13' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section14' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section15' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'tbl_company',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit',
'view_pdf' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field5' => array( 'field' => 'PrimaryPhone',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field21' => array( 'field' => 'PrimaryFax',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'SalesRepID',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 'CreditApprovalStatus',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field8' => array( 'field' => 'Insurance',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'Comments',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field' => array( 'field' => 'ReferenceNumber',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field3' => array( 'field' => 'CustomerNumber',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field2' => array( 'field' => 'BusinessNumber',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field12' => array( 'field' => 'INCOTermsID',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field13' => array( 'field' => 'INCOTermsDescription',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field14' => array( 'field' => 'PaymentTermsID',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field9' => array( 'field' => 'CADBankInstitutionNumber',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field10' => array( 'field' => 'CADBankroutingNumber',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'CADBankAccountNumber',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'tbl_address',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'tbl_documents',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'tb_contacts',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview3' => array( 'type' => 'details_preview',
'table' => 'tbl_company_equipment',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'logo1' => array( 'type' => 'logo' ),
'details_preview4' => array( 'type' => 'details_preview',
'table' => 'tbl_company_areas',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview5' => array( 'type' => 'details_preview',
'table' => 'tbl_users',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'General',
'type' => 0 ),
'location' => 'section10' ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'References',
'type' => 0 ),
'location' => 'section11' ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Terms',
'type' => 0 ),
'location' => 'section12' ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Banking',
'type' => 0 ),
'location' => 'section13' ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Address',
'type' => 0 ),
'location' => 'section14' ),
'section5' => array( 'type' => 'section',
'title' => array( 'text' => 'Contacts',
'type' => 0 ),
'location' => 'section15' ),
'section6' => array( 'type' => 'section',
'title' => array( 'text' => 'Attachments',
'type' => 0 ),
'location' => 'section' ),
'section7' => array( 'type' => 'section',
'title' => array( 'text' => 'Equipment',
'type' => 0 ),
'location' => 'section1' ),
'section8' => array( 'type' => 'section',
'title' => array( 'text' => 'Areas Served',
'type' => 0 ),
'location' => 'section2' ),
'section9' => array( 'type' => 'section',
'title' => array( 'text' => 'Users',
'type' => 0 ),
'location' => 'section3' ),
'view_pdf' => array( 'type' => 'view_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'integrated_edit_field1' => array( 'field' => 'Type',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field15' => array( 'field' => 'CarrierSCAC_Number',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field16' => array( 'field' => 'CarrierDOT_Number',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field17' => array( 'field' => 'CarrierMC_Number',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field18' => array( 'field' => 'CarrierDunns_Number',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field19' => array( 'field' => 'CarrierInsuranceCargoPolicyNumber',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field20' => array( 'field' => 'CarrierInsuranceCargoAmount',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field22' => array( 'field' => 'CarrierInsuranceCargoStartDate',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field23' => array( 'field' => 'CarrierInsuranceCargoExpiryDate',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field24' => array( 'field' => 'CarrierInsuranceLiabilityPolicyNumber',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field25' => array( 'field' => 'CarrierInsuranceLiabilityAmount',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field26' => array( 'field' => 'CarrierInsuranceLiabilityStartDate',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field27' => array( 'field' => 'CarrierInsuranceLiabilityExpiryDate',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 7 );
		?>