<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ID',
'companyID',
'RFQStatusID',
'Inbound',
'PONumber',
'BOLNumber',
'ShipperID',
'ShipperReferenceNo',
'ShipperName',
'ShipperAddress1',
'ShipperAddress2',
'ShipperCity',
'ShipperProvinceID',
'ShipperCountryID',
'ShipperCountyName',
'ShipperPostal',
'ShipperLongitude',
'ShipperLatitude',
'ShipperContactName',
'ShipperContactTel',
'ShipperContactFax',
'ShipperContactEmail',
'ConsigneeID',
'ConsigneeReferenceNo',
'ConsigneeName',
'ConsigneeAddress1',
'ConsigneeAddress2',
'ConsigneeCity',
'ConsigneeProvinceID',
'ConsigneeCountryID',
'ConsigneeCountyName',
'ConsigneePostal',
'ConsigneeLongitude',
'ConsigneeLatitude',
'ConsigneeContactName',
'ConsigneeContactTel',
'ConsigneeContactFax',
'ConsigneeContactEmail',
'CarrierID',
'CarrierReferenceNo',
'CarrierName',
'CarrierContactName',
'CarrierContactTel',
'CarrierContactFax',
'CarrierContactEmail',
'CarrierDriver',
'RFQNumber',
'CustomsBrokerID',
'CustomsBrokerName',
'CustomsBrokerContactName',
'CustomsBrokerContactTel',
'CustomsBrokerContactFax',
'CustomsBrokerContactEmail',
'PickupDateExpected',
'NewRFQ',
'DeliveryDateExpected',
'RFQResponseDate',
'PaymentTerms',
'EquipmentType',
'Routing',
'Instructions',
'Price',
'Cost',
'Created',
'BillToPartyID',
'BillToPartyReferenceNo',
'BillToPartyName',
'BillToPartyAddress1',
'BillToPartyAddress2',
'BillToPartyCity',
'BillToPartyProvinceID',
'BillToPartyCountryID',
'BillToPartyPostal',
'BillToPartyContactName',
'BillToPartyContactTel',
'BillToPartyContactFax',
'BillToPartyContactEmail',
'Terms',
'Modified',
'Status',
'ShipperContactID',
'ConsigneeContactID',
'CarrierContactID',
'BillToContactID',
'CustomsContactID',
'ShipperInstructions',
'ConsigneeInstructions',
'ShipperPrimaryContactDetails',
'ShipperAddress',
'ConsigneeAddress',
'ConsigneeContactDetails',
'CarrierContactDetails',
'CustomsBrokerContactDetails',
'BillToAddress',
'BillToContactDetails' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'integrated_search_field' ),
'companyID' => array( 'integrated_search_field1' ),
'RFQStatusID' => array( 'integrated_search_field2' ),
'Inbound' => array( 'integrated_search_field3' ),
'PONumber' => array( 'integrated_search_field4' ),
'BOLNumber' => array( 'integrated_search_field5' ),
'ShipperID' => array( 'integrated_search_field6' ),
'ShipperReferenceNo' => array( 'integrated_search_field7' ),
'ShipperName' => array( 'integrated_search_field8' ),
'ShipperAddress1' => array( 'integrated_search_field9' ),
'ShipperAddress2' => array( 'integrated_search_field10' ),
'ShipperCity' => array( 'integrated_search_field11' ),
'ShipperProvinceID' => array( 'integrated_search_field12' ),
'ShipperCountryID' => array( 'integrated_search_field13' ),
'ShipperCountyName' => array( 'integrated_search_field14' ),
'ShipperPostal' => array( 'integrated_search_field15' ),
'ShipperLongitude' => array( 'integrated_search_field16' ),
'ShipperLatitude' => array( 'integrated_search_field17' ),
'ShipperContactName' => array( 'integrated_search_field18' ),
'ShipperContactTel' => array( 'integrated_search_field19' ),
'ShipperContactFax' => array( 'integrated_search_field20' ),
'ShipperContactEmail' => array( 'integrated_search_field21' ),
'ConsigneeID' => array( 'integrated_search_field22' ),
'ConsigneeReferenceNo' => array( 'integrated_search_field23' ),
'ConsigneeName' => array( 'integrated_search_field24' ),
'ConsigneeAddress1' => array( 'integrated_search_field25' ),
'ConsigneeAddress2' => array( 'integrated_search_field26' ),
'ConsigneeCity' => array( 'integrated_search_field27' ),
'ConsigneeProvinceID' => array( 'integrated_search_field28' ),
'ConsigneeCountryID' => array( 'integrated_search_field29' ),
'ConsigneeCountyName' => array( 'integrated_search_field30' ),
'ConsigneePostal' => array( 'integrated_search_field31' ),
'ConsigneeLongitude' => array( 'integrated_search_field32' ),
'ConsigneeLatitude' => array( 'integrated_search_field33' ),
'ConsigneeContactName' => array( 'integrated_search_field34' ),
'ConsigneeContactTel' => array( 'integrated_search_field35' ),
'ConsigneeContactFax' => array( 'integrated_search_field36' ),
'ConsigneeContactEmail' => array( 'integrated_search_field37' ),
'CarrierID' => array( 'integrated_search_field38' ),
'CarrierReferenceNo' => array( 'integrated_search_field39' ),
'CarrierName' => array( 'integrated_search_field40' ),
'CarrierContactName' => array( 'integrated_search_field41' ),
'CarrierContactTel' => array( 'integrated_search_field42' ),
'CarrierContactFax' => array( 'integrated_search_field43' ),
'CarrierContactEmail' => array( 'integrated_search_field44' ),
'CarrierDriver' => array( 'integrated_search_field45' ),
'RFQNumber' => array( 'integrated_search_field46' ),
'CustomsBrokerID' => array( 'integrated_search_field47' ),
'CustomsBrokerName' => array( 'integrated_search_field48' ),
'CustomsBrokerContactName' => array( 'integrated_search_field49' ),
'CustomsBrokerContactTel' => array( 'integrated_search_field50' ),
'CustomsBrokerContactFax' => array( 'integrated_search_field51' ),
'CustomsBrokerContactEmail' => array( 'integrated_search_field52' ),
'PickupDateExpected' => array( 'integrated_search_field53' ),
'NewRFQ' => array( 'integrated_search_field54' ),
'DeliveryDateExpected' => array( 'integrated_search_field55' ),
'RFQResponseDate' => array( 'integrated_search_field56' ),
'PaymentTerms' => array( 'integrated_search_field59' ),
'EquipmentType' => array( 'integrated_search_field60' ),
'Routing' => array( 'integrated_search_field61' ),
'Instructions' => array( 'integrated_search_field62' ),
'Price' => array( 'integrated_search_field63' ),
'Cost' => array( 'integrated_search_field67' ),
'Created' => array( 'integrated_search_field68' ),
'BillToPartyID' => array( 'integrated_search_field70' ),
'BillToPartyReferenceNo' => array( 'integrated_search_field71' ),
'BillToPartyName' => array( 'integrated_search_field72' ),
'BillToPartyAddress1' => array( 'integrated_search_field73' ),
'BillToPartyAddress2' => array( 'integrated_search_field74' ),
'BillToPartyCity' => array( 'integrated_search_field75' ),
'BillToPartyProvinceID' => array( 'integrated_search_field76' ),
'BillToPartyCountryID' => array( 'integrated_search_field77' ),
'BillToPartyPostal' => array( 'integrated_search_field78' ),
'BillToPartyContactName' => array( 'integrated_search_field79' ),
'BillToPartyContactTel' => array( 'integrated_search_field80' ),
'BillToPartyContactFax' => array( 'integrated_search_field81' ),
'BillToPartyContactEmail' => array( 'integrated_search_field82' ),
'Terms' => array( 'integrated_search_field83' ),
'Modified' => array( 'integrated_search_field85' ),
'Status' => array( 'integrated_search_field89' ),
'ShipperContactID' => array( 'integrated_search_field57' ),
'ConsigneeContactID' => array( 'integrated_search_field58' ),
'CarrierContactID' => array( 'integrated_search_field64' ),
'BillToContactID' => array( 'integrated_search_field65' ),
'CustomsContactID' => array( 'integrated_search_field66' ),
'ShipperInstructions' => array( 'integrated_search_field69' ),
'ConsigneeInstructions' => array( 'integrated_search_field84' ),
'ShipperPrimaryContactDetails' => array( 'integrated_search_field86' ),
'ShipperAddress' => array( 'integrated_search_field87' ),
'ConsigneeAddress' => array( 'integrated_search_field88' ),
'ConsigneeContactDetails' => array( 'integrated_search_field90' ),
'CarrierContactDetails' => array( 'integrated_search_field91' ),
'CustomsBrokerContactDetails' => array( 'integrated_search_field92' ),
'BillToAddress' => array( 'integrated_search_field93' ),
'BillToContactDetails' => array( 'integrated_search_field94' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'search_header' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field55',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field85',
'integrated_search_field89',
'integrated_search_field2',
'integrated_search_field46',
'integrated_search_field54',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field69',
'integrated_search_field84',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_header' => 'top',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field41' => 'grid',
'integrated_search_field42' => 'grid',
'integrated_search_field43' => 'grid',
'integrated_search_field44' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field47' => 'grid',
'integrated_search_field48' => 'grid',
'integrated_search_field49' => 'grid',
'integrated_search_field50' => 'grid',
'integrated_search_field51' => 'grid',
'integrated_search_field52' => 'grid',
'integrated_search_field53' => 'grid',
'integrated_search_field55' => 'grid',
'integrated_search_field59' => 'grid',
'integrated_search_field60' => 'grid',
'integrated_search_field61' => 'grid',
'integrated_search_field62' => 'grid',
'integrated_search_field63' => 'grid',
'integrated_search_field67' => 'grid',
'integrated_search_field68' => 'grid',
'integrated_search_field70' => 'grid',
'integrated_search_field71' => 'grid',
'integrated_search_field72' => 'grid',
'integrated_search_field73' => 'grid',
'integrated_search_field74' => 'grid',
'integrated_search_field75' => 'grid',
'integrated_search_field76' => 'grid',
'integrated_search_field77' => 'grid',
'integrated_search_field78' => 'grid',
'integrated_search_field79' => 'grid',
'integrated_search_field80' => 'grid',
'integrated_search_field81' => 'grid',
'integrated_search_field82' => 'grid',
'integrated_search_field83' => 'grid',
'integrated_search_field85' => 'grid',
'integrated_search_field89' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field54' => 'grid',
'integrated_search_field56' => 'grid',
'integrated_search_field57' => 'grid',
'integrated_search_field58' => 'grid',
'integrated_search_field64' => 'grid',
'integrated_search_field65' => 'grid',
'integrated_search_field66' => 'grid',
'integrated_search_field69' => 'grid',
'integrated_search_field84' => 'grid',
'integrated_search_field86' => 'grid',
'integrated_search_field87' => 'grid',
'integrated_search_field88' => 'grid',
'integrated_search_field90' => 'grid',
'integrated_search_field91' => 'grid',
'integrated_search_field92' => 'grid',
'integrated_search_field93' => 'grid',
'integrated_search_field94' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field70' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field71' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field72' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field73' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field74' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field75' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field76' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field77' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field78' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field79' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field80' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field81' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field82' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field83' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field85' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field89' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field84' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field86' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field87' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field88' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field90' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field91' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field92' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field93' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field94' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field85',
'integrated_search_field89',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field69',
'integrated_search_field84',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field55',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field85',
'integrated_search_field89',
'integrated_search_field2',
'integrated_search_field46',
'integrated_search_field54',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field69',
'integrated_search_field84',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field55',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field85',
'integrated_search_field89',
'integrated_search_field2',
'integrated_search_field46',
'integrated_search_field54',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field69',
'integrated_search_field84',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94' ) ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_search_field' => array( 'field' => 'ID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'companyID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'RFQStatusID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'Inbound',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'PONumber',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'BOLNumber',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'ShipperID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'ShipperReferenceNo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'ShipperName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'ShipperAddress1',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'ShipperAddress2',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'ShipperCity',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'ShipperProvinceID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'ShipperCountryID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'ShipperCountyName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'ShipperPostal',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'ShipperLongitude',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'ShipperLatitude',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'ShipperContactName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'ShipperContactTel',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'ShipperContactFax',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'ShipperContactEmail',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'ConsigneeID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'ConsigneeReferenceNo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'ConsigneeName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'ConsigneeAddress1',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'ConsigneeAddress2',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'ConsigneeCity',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'ConsigneeProvinceID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'ConsigneeCountryID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'ConsigneeCountyName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'ConsigneePostal',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'ConsigneeLongitude',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'ConsigneeLatitude',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'ConsigneeContactName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'ConsigneeContactTel',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'ConsigneeContactFax',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'ConsigneeContactEmail',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'CarrierID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'CarrierReferenceNo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'CarrierName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field41' => array( 'field' => 'CarrierContactName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field42' => array( 'field' => 'CarrierContactTel',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field43' => array( 'field' => 'CarrierContactFax',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field44' => array( 'field' => 'CarrierContactEmail',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field45' => array( 'field' => 'CarrierDriver',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field46' => array( 'field' => 'RFQNumber',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field47' => array( 'field' => 'CustomsBrokerID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field48' => array( 'field' => 'CustomsBrokerName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field49' => array( 'field' => 'CustomsBrokerContactName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field50' => array( 'field' => 'CustomsBrokerContactTel',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field51' => array( 'field' => 'CustomsBrokerContactFax',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field52' => array( 'field' => 'CustomsBrokerContactEmail',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field53' => array( 'field' => 'PickupDateExpected',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field54' => array( 'field' => 'NewRFQ',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field55' => array( 'field' => 'DeliveryDateExpected',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field56' => array( 'field' => 'RFQResponseDate',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field59' => array( 'field' => 'PaymentTerms',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field60' => array( 'field' => 'EquipmentType',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field61' => array( 'field' => 'Routing',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field62' => array( 'field' => 'Instructions',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field63' => array( 'field' => 'Price',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field67' => array( 'field' => 'Cost',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field68' => array( 'field' => 'Created',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field70' => array( 'field' => 'BillToPartyID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field71' => array( 'field' => 'BillToPartyReferenceNo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field72' => array( 'field' => 'BillToPartyName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field73' => array( 'field' => 'BillToPartyAddress1',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field74' => array( 'field' => 'BillToPartyAddress2',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field75' => array( 'field' => 'BillToPartyCity',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field76' => array( 'field' => 'BillToPartyProvinceID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field77' => array( 'field' => 'BillToPartyCountryID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field78' => array( 'field' => 'BillToPartyPostal',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field79' => array( 'field' => 'BillToPartyContactName',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field80' => array( 'field' => 'BillToPartyContactTel',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field81' => array( 'field' => 'BillToPartyContactFax',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field82' => array( 'field' => 'BillToPartyContactEmail',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field83' => array( 'field' => 'Terms',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field85' => array( 'field' => 'Modified',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field89' => array( 'field' => 'Status',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field57' => array( 'field' => 'ShipperContactID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field58' => array( 'field' => 'ConsigneeContactID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field64' => array( 'field' => 'CarrierContactID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field65' => array( 'field' => 'BillToContactID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field66' => array( 'field' => 'CustomsContactID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field69' => array( 'field' => 'ShipperInstructions',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field84' => array( 'field' => 'ConsigneeInstructions',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field86' => array( 'field' => 'ShipperPrimaryContactDetails',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field87' => array( 'field' => 'ShipperAddress',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field88' => array( 'field' => 'ConsigneeAddress',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field90' => array( 'field' => 'ConsigneeContactDetails',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field91' => array( 'field' => 'CarrierContactDetails',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field92' => array( 'field' => 'CustomsBrokerContactDetails',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field93' => array( 'field' => 'BillToAddress',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field94' => array( 'field' => 'BillToContactDetails',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 7 );
		?>