<?php
			$optionsArray = array( 'details' => array( 'tbl_rfq_items' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tbl_rfq_carrier_quote' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'ConsigneeHoursOpen',
'EquipmentType',
'Instructions',
'ShipperInstructions',
'ShipperHoursOpen',
'ShipperHoursClose',
'DeliveryDateExpected',
'PickupDateExpected',
'RFQResponseDate',
'ConsigneeInstructions',
'ShipperDirections',
'Routing',
'RFQStatusID',
'ConsigneeHoursClose',
'ConsigneeDirections',
'ShipperAddress',
'ConsigneeAddress' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'ConsigneeHoursOpen' => array( 'integrated_edit_field43' ),
'EquipmentType' => array( 'integrated_edit_field59',
'edit_field_tooltip3',
'edit_field_label3' ),
'Instructions' => array( 'integrated_edit_field61',
'edit_field_tooltip4',
'edit_field_label4' ),
'ShipperInstructions' => array( 'integrated_edit_field37' ),
'ShipperHoursOpen' => array( 'integrated_edit_field40' ),
'ShipperHoursClose' => array( 'integrated_edit_field41' ),
'DeliveryDateExpected' => array( 'integrated_edit_field54' ),
'PickupDateExpected' => array( 'integrated_edit_field52' ),
'RFQResponseDate' => array( 'integrated_edit_field55' ),
'ConsigneeInstructions' => array( 'integrated_edit_field39' ),
'ShipperDirections' => array( 'integrated_edit_field42' ),
'Routing' => array( 'integrated_edit_field60' ),
'RFQStatusID' => array( 'integrated_edit_field1' ),
'ConsigneeHoursClose' => array( 'integrated_edit_field44' ),
'ConsigneeDirections' => array( 'integrated_edit_field45' ),
'ShipperAddress' => array( 'integrated_edit_field47' ),
'ConsigneeAddress' => array( 'integrated_edit_field48' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'edit_header' ),
'grid' => array( 'integrated_edit_field1',
'tabs' ),
'section' => array( 'edit_field_label3',
'edit_field_label4',
'edit_field_tooltip4',
'integrated_edit_field59',
'integrated_edit_field61',
'edit_field_tooltip3' ),
'section1' => array( 'integrated_edit_field60' ),
'section2' => array( 'integrated_edit_field47',
'section1',
'integrated_edit_field37',
'integrated_edit_field42' ),
'section3' => array( 'integrated_edit_field48',
'section2',
'integrated_edit_field39',
'integrated_edit_field45' ),
'section8' => array( 'integrated_edit_field55',
'integrated_edit_field52',
'integrated_edit_field54' ),
'section4' => array( 'details_preview1' ),
'section5' => array( 'details_preview' ),
'section9' => array( 'integrated_edit_field40',
'integrated_edit_field41' ),
'section10' => array( 'integrated_edit_field43',
'integrated_edit_field44' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'edit_header' => 'top',
'integrated_edit_field1' => 'grid',
'tabs' => 'grid',
'edit_field_label3' => 'section',
'edit_field_label4' => 'section',
'edit_field_tooltip4' => 'section',
'integrated_edit_field59' => 'section',
'integrated_edit_field61' => 'section',
'edit_field_tooltip3' => 'section',
'integrated_edit_field60' => 'section1',
'integrated_edit_field47' => 'section2',
'section1' => 'section2',
'integrated_edit_field37' => 'section2',
'integrated_edit_field42' => 'section2',
'integrated_edit_field48' => 'section3',
'section2' => 'section3',
'integrated_edit_field39' => 'section3',
'integrated_edit_field45' => 'section3',
'integrated_edit_field55' => 'section8',
'integrated_edit_field52' => 'section8',
'integrated_edit_field54' => 'section8',
'details_preview1' => 'section4',
'details_preview' => 'section5',
'integrated_edit_field40' => 'section9',
'integrated_edit_field41' => 'section9',
'integrated_edit_field43' => 'section10',
'integrated_edit_field44' => 'section10' ),
'itemLocations' => array( 'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_label3' => array( 'location' => 'section',
'cellId' => 'c3' ),
'edit_field_label4' => array( 'location' => 'section',
'cellId' => 'c4' ),
'edit_field_tooltip4' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field59' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field61' => array( 'location' => 'section',
'cellId' => 'c9' ),
'edit_field_tooltip3' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field60' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field47' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'section1' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field37' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field42' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field48' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'section2' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field39' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field45' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field55' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field52' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field54' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'details_preview1' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'details_preview' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field40' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field41' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field43' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field44' => array( 'location' => 'section10',
'cellId' => 'c1' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field43',
'integrated_edit_field37',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field54',
'integrated_edit_field52',
'integrated_edit_field55',
'integrated_edit_field39',
'integrated_edit_field42',
'integrated_edit_field60',
'integrated_edit_field1',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field47',
'integrated_edit_field48' ),
'edit_field' => array( 'integrated_edit_field59',
'integrated_edit_field61' ),
'edit_field_tooltip' => array( 'edit_field_tooltip3',
'edit_field_tooltip4' ),
'section' => array( 'section1',
'section2' ),
'details_preview' => array( 'details_preview',
'details_preview1' ),
'edit_field_label' => array( 'edit_field_label4',
'edit_field_label3' ),
'tabs' => array( 'tabs' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'EquipmentType_fieldblock' ),
'items' => array( 'edit_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field59' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_tooltip3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_label4',
'edit_field_tooltip4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field61' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 2 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field60' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field47',
'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37',
'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field48',
'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39',
'integrated_edit_field45' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field55',
'integrated_edit_field52',
'integrated_edit_field54' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40',
'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43',
'integrated_edit_field44' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'CarrierQuote',
'type' => 'edit',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1',
'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c13' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c9',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'edit_field_label3' ),
'align' => 'right' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'edit_field_label4',
'edit_field_tooltip4' ),
'align' => 'right' ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field59' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field61' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'edit_field_tooltip3' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field60' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field47',
'section1' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37',
'integrated_edit_field42' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field48',
'section2' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39',
'integrated_edit_field45' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field55',
'integrated_edit_field52',
'integrated_edit_field54' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40',
'integrated_edit_field41' ),
'orientation' => 'horizontal' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43',
'integrated_edit_field44' ),
'orientation' => 'horizontal' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field43' => array( 'field' => 'ConsigneeHoursOpen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field59' => array( 'field' => 'EquipmentType',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field61' => array( 'field' => 'Instructions',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'edit_field_tooltip3' => array( 'type' => 'edit_field_tooltip',
'field' => 'EquipmentType',
'separated' => true ),
'integrated_edit_field37' => array( 'field' => 'ShipperInstructions',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Hours of Operation',
'type' => 0 ),
'location' => 'section9' ),
'integrated_edit_field40' => array( 'field' => 'ShipperHoursOpen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'ShipperHoursClose',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'tbl_rfq_carrier_quote',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'tbl_rfq_items',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'integrated_edit_field54' => array( 'field' => 'DeliveryDateExpected',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field52' => array( 'field' => 'PickupDateExpected',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_field_tooltip4' => array( 'type' => 'edit_field_tooltip',
'field' => 'Instructions',
'separated' => true ),
'integrated_edit_field55' => array( 'field' => 'RFQResponseDate',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'ConsigneeInstructions',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field42' => array( 'field' => 'ShipperDirections',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field60' => array( 'field' => 'Routing',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_field_label4' => array( 'type' => 'edit_field_label',
'field' => 'Instructions',
'separated' => true ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'EquipmentType',
'separated' => true ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'General',
'type' => 0 ),
array( 'text' => 'References',
'type' => 0 ),
array( 'text' => 'Shipper',
'type' => 0 ),
array( 'text' => 'Consignee',
'type' => 0 ),
array( 'text' => 'Dates',
'type' => 0 ),
array( 'text' => 'Items',
'type' => 0 ),
array( 'text' => 'Quotations',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2',
'section3',
'section8',
'section4',
'section5' ) ),
'integrated_edit_field1' => array( 'field' => 'RFQStatusID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'ConsigneeHoursClose',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'ConsigneeDirections',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Hours of Operation',
'type' => 0 ),
'location' => 'section10' ),
'integrated_edit_field47' => array( 'field' => 'ShipperAddress',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field48' => array( 'field' => 'ConsigneeAddress',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 7 );
		?>