<?php
			$optionsArray = array( 'totals' => array( 'ID' => array( 'totalsType' => '' ),
'companyID' => array( 'totalsType' => '' ),
'RFQStatusID' => array( 'totalsType' => '' ),
'Inbound' => array( 'totalsType' => '' ),
'PONumber' => array( 'totalsType' => '' ),
'BOLNumber' => array( 'totalsType' => '' ),
'ShipperID' => array( 'totalsType' => '' ),
'ShipperReferenceNo' => array( 'totalsType' => '' ),
'ShipperName' => array( 'totalsType' => '' ),
'ShipperAddress' => array( 'totalsType' => '' ),
'ShipperAddress1' => array( 'totalsType' => '' ),
'ShipperAddress2' => array( 'totalsType' => '' ),
'ShipperCity' => array( 'totalsType' => '' ),
'ShipperProvinceID' => array( 'totalsType' => '' ),
'ShipperCountryID' => array( 'totalsType' => '' ),
'ShipperCountyName' => array( 'totalsType' => '' ),
'ShipperPostal' => array( 'totalsType' => '' ),
'ShipperLongitude' => array( 'totalsType' => '' ),
'ShipperLatitude' => array( 'totalsType' => '' ),
'ShipperContactID' => array( 'totalsType' => '' ),
'ShipperContactName' => array( 'totalsType' => '' ),
'ShipperPrimaryContactDetails' => array( 'totalsType' => '' ),
'ShipperContactTel' => array( 'totalsType' => '' ),
'ShipperContactFax' => array( 'totalsType' => '' ),
'ShipperContactEmail' => array( 'totalsType' => '' ),
'ShipperHoursOpen' => array( 'totalsType' => '' ),
'ShipperHoursClose' => array( 'totalsType' => '' ),
'ShipperInstructions' => array( 'totalsType' => '' ),
'ShipperDirections' => array( 'totalsType' => '' ),
'ConsigneeID' => array( 'totalsType' => '' ),
'ConsigneeReferenceNo' => array( 'totalsType' => '' ),
'ConsigneeName' => array( 'totalsType' => '' ),
'ConsigneeAddress' => array( 'totalsType' => '' ),
'ConsigneeAddress1' => array( 'totalsType' => '' ),
'ConsigneeAddress2' => array( 'totalsType' => '' ),
'ConsigneeCity' => array( 'totalsType' => '' ),
'ConsigneeProvinceID' => array( 'totalsType' => '' ),
'ConsigneeCountryID' => array( 'totalsType' => '' ),
'ConsigneeCountyName' => array( 'totalsType' => '' ),
'ConsigneePostal' => array( 'totalsType' => '' ),
'ConsigneeLongitude' => array( 'totalsType' => '' ),
'ConsigneeLatitude' => array( 'totalsType' => '' ),
'ConsigneeContactID' => array( 'totalsType' => '' ),
'ConsigneeContactDetails' => array( 'totalsType' => '' ),
'ConsigneeContactName' => array( 'totalsType' => '' ),
'ConsigneeContactTel' => array( 'totalsType' => '' ),
'ConsigneeContactFax' => array( 'totalsType' => '' ),
'ConsigneeContactEmail' => array( 'totalsType' => '' ),
'ConsigneeHoursOpen' => array( 'totalsType' => '' ),
'ConsigneeHoursClose' => array( 'totalsType' => '' ),
'ConsigneeInstructions' => array( 'totalsType' => '' ),
'ConsigneeDirections' => array( 'totalsType' => '' ),
'CarrierID' => array( 'totalsType' => '' ),
'CarrierReferenceNo' => array( 'totalsType' => '' ),
'CarrierName' => array( 'totalsType' => '' ),
'CarrierContactID' => array( 'totalsType' => '' ),
'CarrierContactDetails' => array( 'totalsType' => '' ),
'CarrierContactName' => array( 'totalsType' => '' ),
'CarrierContactTel' => array( 'totalsType' => '' ),
'CarrierContactFax' => array( 'totalsType' => '' ),
'CarrierContactEmail' => array( 'totalsType' => '' ),
'CarrierDriver' => array( 'totalsType' => '' ),
'CustomsBrokerID' => array( 'totalsType' => '' ),
'CustomsBrokerName' => array( 'totalsType' => '' ),
'CustomsContactID' => array( 'totalsType' => '' ),
'CustomsBrokerContactDetails' => array( 'totalsType' => '' ),
'CustomsBrokerContactName' => array( 'totalsType' => '' ),
'CustomsBrokerContactTel' => array( 'totalsType' => '' ),
'CustomsBrokerContactFax' => array( 'totalsType' => '' ),
'CustomsBrokerContactEmail' => array( 'totalsType' => '' ),
'PickupDateExpected' => array( 'totalsType' => '' ),
'DeliveryDateExpected' => array( 'totalsType' => '' ),
'PaymentTerms' => array( 'totalsType' => '' ),
'EquipmentType' => array( 'totalsType' => '' ),
'Routing' => array( 'totalsType' => '' ),
'Instructions' => array( 'totalsType' => '' ),
'Price' => array( 'totalsType' => '' ),
'Cost' => array( 'totalsType' => '' ),
'Created' => array( 'totalsType' => '' ),
'RFQNumber' => array( 'totalsType' => '' ),
'BillToPartyID' => array( 'totalsType' => '' ),
'BillToPartyReferenceNo' => array( 'totalsType' => '' ),
'BillToPartyName' => array( 'totalsType' => '' ),
'BillToAddress' => array( 'totalsType' => '' ),
'BillToPartyAddress1' => array( 'totalsType' => '' ),
'BillToPartyAddress2' => array( 'totalsType' => '' ),
'BillToPartyCity' => array( 'totalsType' => '' ),
'BillToPartyProvinceID' => array( 'totalsType' => '' ),
'BillToPartyCountryID' => array( 'totalsType' => '' ),
'BillToPartyPostal' => array( 'totalsType' => '' ),
'BillToContactID' => array( 'totalsType' => '' ),
'BillToContactDetails' => array( 'totalsType' => '' ),
'BillToPartyContactName' => array( 'totalsType' => '' ),
'BillToPartyContactTel' => array( 'totalsType' => '' ),
'BillToPartyContactFax' => array( 'totalsType' => '' ),
'BillToPartyContactEmail' => array( 'totalsType' => '' ),
'Terms' => array( 'totalsType' => '' ),
'Modified' => array( 'totalsType' => '' ),
'Status' => array( 'totalsType' => '' ),
'NewRFQ' => array( 'totalsType' => '' ),
'RFQResponseDate' => array( 'totalsType' => '' ),
'OrderID' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array(  ),
'exportFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array(  ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ),
'grid' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ) ),
'dbProps' => array(  ),
'version' => 7,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>