<?php
			$optionsArray = array( 'details' => array( 'tbl_address' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'tbl_documents' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'tb_contacts' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'tbl_company_equipment' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'tbl_company_areas' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'tbl_users' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'Name',
'PrimaryPhone',
'PrimaryFax',
'CreditApprovalStatus',
'SalesRepID',
'Insurance',
'Comments',
'CustomerNumber',
'ReferenceNumber',
'BusinessNumber',
'INCOTermsID',
'INCOTermsDescription',
'PaymentTermsID',
'CADBankInstitutionNumber',
'CADBankroutingNumber',
'CADBankAccountNumber',
'PrimaryAddress1',
'PrimaryAddress2',
'PrimaryCity',
'PrimaryPostalCode',
'PrimaryCountry',
'PrimaryProvince',
'Type' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Name' => array( 'integrated_edit_field1' ),
'PrimaryPhone' => array( 'integrated_edit_field20' ),
'PrimaryFax' => array( 'integrated_edit_field21' ),
'CreditApprovalStatus' => array( 'integrated_edit_field7' ),
'SalesRepID' => array( 'integrated_edit_field6' ),
'Insurance' => array( 'integrated_edit_field8' ),
'Comments' => array( 'integrated_edit_field4' ),
'CustomerNumber' => array( 'integrated_edit_field3' ),
'ReferenceNumber' => array( 'integrated_edit_field' ),
'BusinessNumber' => array( 'integrated_edit_field2' ),
'INCOTermsID' => array( 'integrated_edit_field12' ),
'INCOTermsDescription' => array( 'integrated_edit_field13' ),
'PaymentTermsID' => array( 'integrated_edit_field14' ),
'CADBankInstitutionNumber' => array( 'integrated_edit_field9' ),
'CADBankroutingNumber' => array( 'integrated_edit_field10' ),
'CADBankAccountNumber' => array( 'integrated_edit_field11' ),
'PrimaryAddress1' => array( 'integrated_edit_field5' ),
'PrimaryAddress2' => array( 'integrated_edit_field15' ),
'PrimaryCity' => array( 'integrated_edit_field16' ),
'PrimaryPostalCode' => array( 'integrated_edit_field17' ),
'PrimaryCountry' => array( 'integrated_edit_field19' ),
'PrimaryProvince' => array( 'integrated_edit_field18' ),
'Type' => array( 'integrated_edit_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'integrated_edit_field1',
'integrated_edit_field22',
'tabs' ),
'section' => array( 'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field4' ),
'section1' => array( 'integrated_edit_field3',
'integrated_edit_field',
'integrated_edit_field2' ),
'section2' => array( 'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14' ),
'section3' => array( 'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'section4' => array( 'integrated_edit_field5',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field18' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field22' => 'grid',
'tabs' => 'grid',
'integrated_edit_field20' => 'section',
'integrated_edit_field21' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field3' => 'section1',
'integrated_edit_field' => 'section1',
'integrated_edit_field2' => 'section1',
'integrated_edit_field12' => 'section2',
'integrated_edit_field13' => 'section2',
'integrated_edit_field14' => 'section2',
'integrated_edit_field9' => 'section3',
'integrated_edit_field10' => 'section3',
'integrated_edit_field11' => 'section3',
'integrated_edit_field5' => 'section4',
'integrated_edit_field15' => 'section4',
'integrated_edit_field16' => 'section4',
'integrated_edit_field17' => 'section4',
'integrated_edit_field19' => 'section4',
'integrated_edit_field18' => 'section4' ),
'itemLocations' => array( 'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field20' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field13' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field17' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field19' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field18' => array( 'location' => 'section4',
'cellId' => 'c1' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field4',
'integrated_edit_field3',
'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field5',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field18',
'integrated_edit_field22' ),
'tabs' => array( 'tabs' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field22',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3',
'integrated_edit_field',
'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field22',
'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3',
'integrated_edit_field',
'integrated_edit_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field18' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'integrated_edit_field1' => array( 'field' => 'Name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'General',
'type' => 0 ),
array( 'text' => 'References',
'type' => 0 ),
array( 'text' => 'Terms',
'type' => 0 ),
array( 'text' => 'Banking',
'type' => 0 ),
array( 'text' => 'Address',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2',
'section3',
'section4' ) ),
'integrated_edit_field20' => array( 'field' => 'PrimaryPhone',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'PrimaryFax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'CreditApprovalStatus',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'SalesRepID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'Insurance',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'Comments',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'CustomerNumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'ReferenceNumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'BusinessNumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'INCOTermsID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'INCOTermsDescription',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'PaymentTermsID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'CADBankInstitutionNumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'CADBankroutingNumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'CADBankAccountNumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'PrimaryAddress1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'PrimaryAddress2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'PrimaryCity',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'PrimaryPostalCode',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'PrimaryCountry',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'PrimaryProvince',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'logo1' => array( 'type' => 'logo' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'integrated_edit_field22' => array( 'field' => 'Type',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 7 );
		?>