<?php
			$optionsArray = array( 'details' => array( 'tbl_order_status' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tbl_order_items' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tbl_order_assesorial' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'companyID',
'Instructions',
'EquipmentType',
'PaymentTerms',
'PONumber',
'OrderNumber',
'QuotationNumber',
'BOLNumber',
'Routing',
'ShipperID',
'ShipperReferenceNo',
'ShipperName',
'ShipperAddress1',
'ShipperAddress2',
'ShipperCity',
'ShipperPostal',
'ShipperProvinceID',
'ShipperCountryID',
'ShipperContactName',
'ShipperContactTel',
'ShipperContactFax',
'ShipperContactEmail',
'ShipperCountyName',
'ShipperLongitude',
'ShipperLatitude',
'ConsigneeID',
'ConsigneeReferenceNo',
'ConsigneeName',
'ConsigneeAddress1',
'ConsigneeAddress2',
'ConsigneeCity',
'ConsigneePostal',
'ConsigneeProvinceID',
'ConsigneeCountryID',
'ConsigneeContactName',
'ConsigneeContactTel',
'ConsigneeContactFax',
'ConsigneeContactEmail',
'ConsigneeCountyName',
'ConsigneeLongitude',
'ConsigneeLatitude',
'BillToPartyID',
'BillToPartyName',
'BillToPartyReferenceNo',
'BillToPartyAddress1',
'BillToPartyAddress2',
'BillToPartyProvinceID',
'BillToPartyCountryID',
'BillToPartyCity',
'BillToPartyPostal',
'BillToPartyContactName',
'BillToPartyContactTel',
'BillToPartyContactFax',
'BillToPartyContactEmail',
'CarrierID',
'CarrierName',
'CarrierReferenceNo',
'CarrierDriver',
'TrailerID',
'CarrierContactName',
'CarrierContactTel',
'CarrierContactFax',
'CarrierContactEmail',
'CustomsBrokerID',
'CustomsBrokerName',
'CustomsBrokerContactName',
'CustomsBrokerContactTel',
'CustomsBrokerContactEmail',
'CustomsBrokerContactFax',
'PickupDateExpected',
'DeliveryDateExpected',
'Price',
'Terms',
'Status',
'Inbound',
'ShipperContactID',
'ConsigneeContactID',
'CarrierContactID',
'CustomsContactID',
'BillToContactID',
'ShipperInstructions',
'ConsigneeInstructions',
'ShipperHoursOpen',
'ShipperHoursClose',
'ShipperDirections',
'ConsigneeHoursOpen',
'ConsigneeHoursClose',
'ConsigneeDirections',
'ShipperAddress',
'ShipperContactDetails',
'ConsigneeAddress',
'ConsigneeContactDetails',
'CarrierContactDetails',
'CustomsBrokerContactDetails',
'BillToAddress',
'BillToContactDetails' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'companyID' => array( 'integrated_edit_field' ),
'Instructions' => array( 'integrated_edit_field56' ),
'EquipmentType' => array( 'integrated_edit_field54' ),
'PaymentTerms' => array( 'integrated_edit_field53' ),
'PONumber' => array( 'integrated_edit_field4' ),
'OrderNumber' => array( 'integrated_edit_field63' ),
'QuotationNumber' => array( 'integrated_edit_field78' ),
'BOLNumber' => array( 'integrated_edit_field5' ),
'Routing' => array( 'integrated_edit_field55' ),
'ShipperID' => array( 'integrated_edit_field6' ),
'ShipperReferenceNo' => array( 'integrated_edit_field7' ),
'ShipperName' => array( 'integrated_edit_field8' ),
'ShipperAddress1' => array( 'integrated_edit_field9' ),
'ShipperAddress2' => array( 'integrated_edit_field10' ),
'ShipperCity' => array( 'integrated_edit_field11' ),
'ShipperPostal' => array( 'integrated_edit_field14' ),
'ShipperProvinceID' => array( 'integrated_edit_field12' ),
'ShipperCountryID' => array( 'integrated_edit_field13' ),
'ShipperContactName' => array( 'integrated_edit_field15' ),
'ShipperContactTel' => array( 'integrated_edit_field16' ),
'ShipperContactFax' => array( 'integrated_edit_field17' ),
'ShipperContactEmail' => array( 'integrated_edit_field18' ),
'ShipperCountyName' => array( 'integrated_edit_field88' ),
'ShipperLongitude' => array( 'integrated_edit_field89' ),
'ShipperLatitude' => array( 'integrated_edit_field90' ),
'ConsigneeID' => array( 'integrated_edit_field19' ),
'ConsigneeReferenceNo' => array( 'integrated_edit_field20' ),
'ConsigneeName' => array( 'integrated_edit_field21' ),
'ConsigneeAddress1' => array( 'integrated_edit_field22' ),
'ConsigneeAddress2' => array( 'integrated_edit_field23' ),
'ConsigneeCity' => array( 'integrated_edit_field24' ),
'ConsigneePostal' => array( 'integrated_edit_field27' ),
'ConsigneeProvinceID' => array( 'integrated_edit_field25' ),
'ConsigneeCountryID' => array( 'integrated_edit_field26' ),
'ConsigneeContactName' => array( 'integrated_edit_field28' ),
'ConsigneeContactTel' => array( 'integrated_edit_field29' ),
'ConsigneeContactFax' => array( 'integrated_edit_field30' ),
'ConsigneeContactEmail' => array( 'integrated_edit_field31' ),
'ConsigneeCountyName' => array( 'integrated_edit_field91' ),
'ConsigneeLongitude' => array( 'integrated_edit_field92' ),
'ConsigneeLatitude' => array( 'integrated_edit_field93' ),
'BillToPartyID' => array( 'integrated_edit_field64' ),
'BillToPartyName' => array( 'integrated_edit_field66' ),
'BillToPartyReferenceNo' => array( 'integrated_edit_field65' ),
'BillToPartyAddress1' => array( 'integrated_edit_field67' ),
'BillToPartyAddress2' => array( 'integrated_edit_field68' ),
'BillToPartyProvinceID' => array( 'integrated_edit_field70' ),
'BillToPartyCountryID' => array( 'integrated_edit_field71' ),
'BillToPartyCity' => array( 'integrated_edit_field69' ),
'BillToPartyPostal' => array( 'integrated_edit_field72' ),
'BillToPartyContactName' => array( 'integrated_edit_field73' ),
'BillToPartyContactTel' => array( 'integrated_edit_field74' ),
'BillToPartyContactFax' => array( 'integrated_edit_field75' ),
'BillToPartyContactEmail' => array( 'integrated_edit_field76' ),
'CarrierID' => array( 'integrated_edit_field32' ),
'CarrierName' => array( 'integrated_edit_field34' ),
'CarrierReferenceNo' => array( 'integrated_edit_field33' ),
'CarrierDriver' => array( 'integrated_edit_field39' ),
'TrailerID' => array( 'integrated_edit_field82' ),
'CarrierContactName' => array( 'integrated_edit_field35' ),
'CarrierContactTel' => array( 'integrated_edit_field36' ),
'CarrierContactFax' => array( 'integrated_edit_field37' ),
'CarrierContactEmail' => array( 'integrated_edit_field38' ),
'CustomsBrokerID' => array( 'integrated_edit_field41' ),
'CustomsBrokerName' => array( 'integrated_edit_field42' ),
'CustomsBrokerContactName' => array( 'integrated_edit_field43' ),
'CustomsBrokerContactTel' => array( 'integrated_edit_field44' ),
'CustomsBrokerContactEmail' => array( 'integrated_edit_field46' ),
'CustomsBrokerContactFax' => array( 'integrated_edit_field45' ),
'PickupDateExpected' => array( 'integrated_edit_field47' ),
'DeliveryDateExpected' => array( 'integrated_edit_field49' ),
'Price' => array( 'integrated_edit_field57' ),
'Terms' => array( 'integrated_edit_field77' ),
'Status' => array( 'integrated_edit_field83' ),
'Inbound' => array( 'integrated_edit_field1' ),
'ShipperContactID' => array( 'integrated_edit_field2' ),
'ConsigneeContactID' => array( 'integrated_edit_field3' ),
'CarrierContactID' => array( 'integrated_edit_field40' ),
'CustomsContactID' => array( 'integrated_edit_field48' ),
'BillToContactID' => array( 'integrated_edit_field50' ),
'ShipperInstructions' => array( 'integrated_edit_field51' ),
'ConsigneeInstructions' => array( 'integrated_edit_field52' ),
'ShipperHoursOpen' => array( 'integrated_edit_field58' ),
'ShipperHoursClose' => array( 'integrated_edit_field59' ),
'ShipperDirections' => array( 'integrated_edit_field60' ),
'ConsigneeHoursOpen' => array( 'integrated_edit_field61' ),
'ConsigneeHoursClose' => array( 'integrated_edit_field62' ),
'ConsigneeDirections' => array( 'integrated_edit_field79' ),
'ShipperAddress' => array( 'integrated_edit_field80' ),
'ShipperContactDetails' => array( 'integrated_edit_field81' ),
'ConsigneeAddress' => array( 'integrated_edit_field84' ),
'ConsigneeContactDetails' => array( 'integrated_edit_field85' ),
'CarrierContactDetails' => array( 'integrated_edit_field86' ),
'CustomsBrokerContactDetails' => array( 'integrated_edit_field87' ),
'BillToAddress' => array( 'integrated_edit_field94' ),
'BillToContactDetails' => array( 'integrated_edit_field95' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'integrated_edit_field',
'tabs',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field40',
'integrated_edit_field48',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field94',
'integrated_edit_field95' ),
'section' => array( 'integrated_edit_field1',
'integrated_edit_field77',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field56',
'integrated_edit_field83' ),
'section1' => array( 'integrated_edit_field4',
'integrated_edit_field63',
'integrated_edit_field78',
'integrated_edit_field5',
'integrated_edit_field55' ),
'section2' => array( 'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90' ),
'section3' => array( 'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field27',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93' ),
'section7' => array( 'integrated_edit_field64',
'integrated_edit_field66',
'integrated_edit_field65',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field69',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76' ),
'section4' => array( 'integrated_edit_field32',
'integrated_edit_field34',
'integrated_edit_field33',
'integrated_edit_field39',
'integrated_edit_field82',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38' ),
'section5' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field46',
'integrated_edit_field45' ),
'section6' => array( 'integrated_edit_field47',
'integrated_edit_field49' ),
'section8' => array( 'details_preview1' ),
'section10' => array( 'integrated_edit_field57',
'details_preview2' ),
'section9' => array( 'details_preview' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field' => 'grid',
'tabs' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field40' => 'grid',
'integrated_edit_field48' => 'grid',
'integrated_edit_field50' => 'grid',
'integrated_edit_field51' => 'grid',
'integrated_edit_field52' => 'grid',
'integrated_edit_field58' => 'grid',
'integrated_edit_field59' => 'grid',
'integrated_edit_field60' => 'grid',
'integrated_edit_field61' => 'grid',
'integrated_edit_field62' => 'grid',
'integrated_edit_field79' => 'grid',
'integrated_edit_field80' => 'grid',
'integrated_edit_field81' => 'grid',
'integrated_edit_field84' => 'grid',
'integrated_edit_field85' => 'grid',
'integrated_edit_field86' => 'grid',
'integrated_edit_field87' => 'grid',
'integrated_edit_field94' => 'grid',
'integrated_edit_field95' => 'grid',
'integrated_edit_field1' => 'section',
'integrated_edit_field77' => 'section',
'integrated_edit_field53' => 'section',
'integrated_edit_field54' => 'section',
'integrated_edit_field56' => 'section',
'integrated_edit_field83' => 'section',
'integrated_edit_field4' => 'section1',
'integrated_edit_field63' => 'section1',
'integrated_edit_field78' => 'section1',
'integrated_edit_field5' => 'section1',
'integrated_edit_field55' => 'section1',
'integrated_edit_field6' => 'section2',
'integrated_edit_field7' => 'section2',
'integrated_edit_field8' => 'section2',
'integrated_edit_field9' => 'section2',
'integrated_edit_field10' => 'section2',
'integrated_edit_field11' => 'section2',
'integrated_edit_field14' => 'section2',
'integrated_edit_field12' => 'section2',
'integrated_edit_field13' => 'section2',
'integrated_edit_field15' => 'section2',
'integrated_edit_field16' => 'section2',
'integrated_edit_field17' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field88' => 'section2',
'integrated_edit_field89' => 'section2',
'integrated_edit_field90' => 'section2',
'integrated_edit_field19' => 'section3',
'integrated_edit_field20' => 'section3',
'integrated_edit_field21' => 'section3',
'integrated_edit_field22' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field24' => 'section3',
'integrated_edit_field27' => 'section3',
'integrated_edit_field25' => 'section3',
'integrated_edit_field26' => 'section3',
'integrated_edit_field28' => 'section3',
'integrated_edit_field29' => 'section3',
'integrated_edit_field30' => 'section3',
'integrated_edit_field31' => 'section3',
'integrated_edit_field91' => 'section3',
'integrated_edit_field92' => 'section3',
'integrated_edit_field93' => 'section3',
'integrated_edit_field64' => 'section7',
'integrated_edit_field66' => 'section7',
'integrated_edit_field65' => 'section7',
'integrated_edit_field67' => 'section7',
'integrated_edit_field68' => 'section7',
'integrated_edit_field70' => 'section7',
'integrated_edit_field71' => 'section7',
'integrated_edit_field69' => 'section7',
'integrated_edit_field72' => 'section7',
'integrated_edit_field73' => 'section7',
'integrated_edit_field74' => 'section7',
'integrated_edit_field75' => 'section7',
'integrated_edit_field76' => 'section7',
'integrated_edit_field32' => 'section4',
'integrated_edit_field34' => 'section4',
'integrated_edit_field33' => 'section4',
'integrated_edit_field39' => 'section4',
'integrated_edit_field82' => 'section4',
'integrated_edit_field35' => 'section4',
'integrated_edit_field36' => 'section4',
'integrated_edit_field37' => 'section4',
'integrated_edit_field38' => 'section4',
'integrated_edit_field41' => 'section5',
'integrated_edit_field42' => 'section5',
'integrated_edit_field43' => 'section5',
'integrated_edit_field44' => 'section5',
'integrated_edit_field46' => 'section5',
'integrated_edit_field45' => 'section5',
'integrated_edit_field47' => 'section6',
'integrated_edit_field49' => 'section6',
'details_preview1' => 'section8',
'integrated_edit_field57' => 'section10',
'details_preview2' => 'section10',
'details_preview' => 'section9' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field79' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field80' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field81' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field84' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field85' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field86' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field87' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field94' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field95' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field77' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field53' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field54' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field56' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field83' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field63' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field78' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field55' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field13' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field16' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field17' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field88' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field89' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field90' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field19' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field20' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field27' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field26' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field28' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field29' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field30' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field31' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field91' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field92' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field93' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field64' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field66' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field65' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field67' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field68' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field70' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field71' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field69' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field72' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field73' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field74' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field75' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field76' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field32' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field33' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field39' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field82' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field35' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field36' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field37' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field38' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field41' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field42' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field43' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field44' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field46' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field45' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field47' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field49' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'details_preview1' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field57' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'details_preview2' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'details_preview' => array( 'location' => 'section9',
'cellId' => 'c1' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field56',
'integrated_edit_field54',
'integrated_edit_field53',
'integrated_edit_field4',
'integrated_edit_field63',
'integrated_edit_field78',
'integrated_edit_field5',
'integrated_edit_field55',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field27',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field64',
'integrated_edit_field66',
'integrated_edit_field65',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field69',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field32',
'integrated_edit_field34',
'integrated_edit_field33',
'integrated_edit_field39',
'integrated_edit_field82',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field46',
'integrated_edit_field45',
'integrated_edit_field47',
'integrated_edit_field49',
'integrated_edit_field57',
'integrated_edit_field77',
'integrated_edit_field83',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field40',
'integrated_edit_field48',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field94',
'integrated_edit_field95' ),
'tabs' => array( 'tabs' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'tabs',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field40',
'integrated_edit_field48',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field94',
'integrated_edit_field95' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field77',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field56',
'integrated_edit_field83' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4',
'integrated_edit_field63',
'integrated_edit_field78',
'integrated_edit_field5',
'integrated_edit_field55' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field12',
'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field27',
'integrated_edit_field25',
'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field64',
'integrated_edit_field66',
'integrated_edit_field65',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field69',
'integrated_edit_field72' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32',
'integrated_edit_field34',
'integrated_edit_field33',
'integrated_edit_field39',
'integrated_edit_field82' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field44',
'integrated_edit_field46',
'integrated_edit_field45' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field47',
'integrated_edit_field49' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field57',
'details_preview2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field',
'tabs',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field40',
'integrated_edit_field48',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field94',
'integrated_edit_field95' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field77',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field56',
'integrated_edit_field83' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4',
'integrated_edit_field63',
'integrated_edit_field78',
'integrated_edit_field5',
'integrated_edit_field55' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field12',
'integrated_edit_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field27',
'integrated_edit_field25',
'integrated_edit_field26' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field64',
'integrated_edit_field66',
'integrated_edit_field65',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field69',
'integrated_edit_field72' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32',
'integrated_edit_field34',
'integrated_edit_field33',
'integrated_edit_field39',
'integrated_edit_field82' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field44',
'integrated_edit_field46',
'integrated_edit_field45' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field47',
'integrated_edit_field49' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field57',
'details_preview2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'integrated_edit_field' => array( 'field' => 'companyID',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'General',
'type' => 0 ),
array( 'text' => 'References',
'type' => 0 ),
array( 'text' => 'Shipper',
'type' => 0 ),
array( 'text' => 'Consignee',
'type' => 0 ),
array( 'text' => 'Bill To',
'type' => 0 ),
array( 'text' => 'Carrier',
'type' => 0 ),
array( 'text' => 'Customs',
'type' => 0 ),
array( 'text' => 'Dates',
'type' => 0 ),
array( 'text' => 'Items',
'type' => 0 ),
array( 'text' => 'Assessorial',
'type' => 0 ),
array( 'text' => 'Status',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2',
'section3',
'section7',
'section4',
'section5',
'section6',
'section8',
'section10',
'section9' ) ),
'integrated_edit_field56' => array( 'field' => 'Instructions',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field54' => array( 'field' => 'EquipmentType',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field53' => array( 'field' => 'PaymentTerms',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'PONumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field63' => array( 'field' => 'OrderNumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field78' => array( 'field' => 'QuotationNumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'BOLNumber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field55' => array( 'field' => 'Routing',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'ShipperID',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 'ShipperReferenceNo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'ShipperName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'ShipperAddress1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'ShipperAddress2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'ShipperCity',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'ShipperPostal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'ShipperProvinceID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'ShipperCountryID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'ShipperContactName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'ShipperContactTel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'ShipperContactFax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'ShipperContactEmail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field88' => array( 'field' => 'ShipperCountyName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field89' => array( 'field' => 'ShipperLongitude',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field90' => array( 'field' => 'ShipperLatitude',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field19' => array( 'field' => 'ConsigneeID',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field20' => array( 'field' => 'ConsigneeReferenceNo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'ConsigneeName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'ConsigneeAddress1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'ConsigneeAddress2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'ConsigneeCity',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'ConsigneePostal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'ConsigneeProvinceID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'ConsigneeCountryID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'ConsigneeContactName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'ConsigneeContactTel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'ConsigneeContactFax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'ConsigneeContactEmail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field91' => array( 'field' => 'ConsigneeCountyName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field92' => array( 'field' => 'ConsigneeLongitude',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field93' => array( 'field' => 'ConsigneeLatitude',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field64' => array( 'field' => 'BillToPartyID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field66' => array( 'field' => 'BillToPartyName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field65' => array( 'field' => 'BillToPartyReferenceNo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field67' => array( 'field' => 'BillToPartyAddress1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field68' => array( 'field' => 'BillToPartyAddress2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field70' => array( 'field' => 'BillToPartyProvinceID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field71' => array( 'field' => 'BillToPartyCountryID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field69' => array( 'field' => 'BillToPartyCity',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field72' => array( 'field' => 'BillToPartyPostal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field73' => array( 'field' => 'BillToPartyContactName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field74' => array( 'field' => 'BillToPartyContactTel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field75' => array( 'field' => 'BillToPartyContactFax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field76' => array( 'field' => 'BillToPartyContactEmail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'CarrierID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'CarrierName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'CarrierReferenceNo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'CarrierDriver',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field82' => array( 'field' => 'TrailerID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'CarrierContactName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'CarrierContactTel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'CarrierContactFax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'CarrierContactEmail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'CustomsBrokerID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'CustomsBrokerName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'CustomsBrokerContactName',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'CustomsBrokerContactTel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'CustomsBrokerContactEmail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'CustomsBrokerContactFax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'PickupDateExpected',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field49' => array( 'field' => 'DeliveryDateExpected',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field57' => array( 'field' => 'Price',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field77' => array( 'field' => 'Terms',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field83' => array( 'field' => 'Status',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'logo1' => array( 'type' => 'logo' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'tbl_order_status',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'tbl_order_items',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'tbl_order_assesorial',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'integrated_edit_field1' => array( 'field' => 'Inbound',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'integrated_edit_field2' => array( 'field' => 'ShipperContactID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'ConsigneeContactID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'CarrierContactID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'CustomsContactID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'BillToContactID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'ShipperInstructions',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field52' => array( 'field' => 'ConsigneeInstructions',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field58' => array( 'field' => 'ShipperHoursOpen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field59' => array( 'field' => 'ShipperHoursClose',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field60' => array( 'field' => 'ShipperDirections',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field61' => array( 'field' => 'ConsigneeHoursOpen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field62' => array( 'field' => 'ConsigneeHoursClose',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field79' => array( 'field' => 'ConsigneeDirections',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field80' => array( 'field' => 'ShipperAddress',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field81' => array( 'field' => 'ShipperContactDetails',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field84' => array( 'field' => 'ConsigneeAddress',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field85' => array( 'field' => 'ConsigneeContactDetails',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field86' => array( 'field' => 'CarrierContactDetails',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field87' => array( 'field' => 'CustomsBrokerContactDetails',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field94' => array( 'field' => 'BillToAddress',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field95' => array( 'field' => 'BillToContactDetails',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 7 );
		?>