<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => true,
'spreadsheetMode' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'ID' => array( 'totalsType' => '' ),
'CustomerID' => array( 'totalsType' => '' ),
'EffectiveDate' => array( 'totalsType' => '' ),
'ExpiryDate' => array( 'totalsType' => '' ),
'IssueDate' => array( 'totalsType' => '' ),
'ShipperName' => array( 'totalsType' => '' ),
'PickupDate' => array( 'totalsType' => '' ),
'DeliveryDate' => array( 'totalsType' => '' ),
'ShipperAddress' => array( 'totalsType' => '' ),
'ConsigneeName' => array( 'totalsType' => '' ),
'ConsigneeAddress' => array( 'totalsType' => '' ),
'CarrierID' => array( 'totalsType' => '' ),
'Instructions' => array( 'totalsType' => '' ),
'RFQResponseDate' => array( 'totalsType' => '' ),
'Description' => array( 'totalsType' => '' ),
'CarrierCompanyID' => array( 'totalsType' => '' ),
'CarrierAddress' => array( 'totalsType' => '' ),
'CarrierPhone' => array( 'totalsType' => '' ),
'CarrierFax' => array( 'totalsType' => '' ),
'EquipmentType' => array( 'totalsType' => '' ),
'ContactDetails' => array( 'totalsType' => '' ),
'SalesRepName' => array( 'totalsType' => '' ),
'SalesRepEmail' => array( 'totalsType' => '' ),
'SalesRepPrimaryPhone' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'ID',
'CustomerID',
'EffectiveDate',
'ExpiryDate',
'IssueDate',
'ShipperName',
'ShipperAddress',
'ConsigneeName',
'ConsigneeAddress',
'CarrierID',
'Instructions',
'RFQResponseDate',
'Description',
'CarrierCompanyID',
'CarrierAddress',
'CarrierPhone',
'CarrierFax',
'EquipmentType',
'ContactDetails',
'PickupDate',
'DeliveryDate',
'SalesRepName',
'SalesRepEmail',
'SalesRepPrimaryPhone' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'CarrierAddress',
'SalesRepPrimaryPhone',
'SalesRepEmail',
'SalesRepName',
'DeliveryDate',
'PickupDate',
'ShipperName',
'ShipperAddress',
'RFQResponseDate',
'IssueDate',
'Instructions',
'ID',
'ExpiryDate',
'EquipmentType',
'EffectiveDate',
'Description',
'CustomerID',
'ContactDetails',
'ConsigneeName',
'ConsigneeAddress',
'CarrierPhone',
'CarrierID',
'CarrierFax',
'CarrierCompanyID' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'PickupDate',
'DeliveryDate',
'SalesRepName',
'SalesRepEmail',
'SalesRepPrimaryPhone' ),
'inlineEditFields' => array( 'ID',
'CustomerID',
'EffectiveDate',
'ExpiryDate',
'IssueDate',
'ShipperName',
'ShipperAddress',
'ConsigneeName',
'ConsigneeAddress',
'CarrierID',
'Instructions',
'RFQResponseDate',
'Description',
'CarrierCompanyID',
'CarrierAddress',
'CarrierPhone',
'CarrierFax',
'EquipmentType',
'ContactDetails',
'PickupDate',
'DeliveryDate',
'SalesRepName',
'SalesRepEmail',
'SalesRepPrimaryPhone' ),
'fieldItems' => array( 'ID' => array( 'simple_grid_field',
'simple_grid_field24' ),
'CustomerID' => array( 'simple_grid_field1',
'simple_grid_field25' ),
'EffectiveDate' => array( 'simple_grid_field2',
'simple_grid_field26' ),
'ExpiryDate' => array( 'simple_grid_field3',
'simple_grid_field27' ),
'IssueDate' => array( 'simple_grid_field4',
'simple_grid_field28' ),
'ShipperName' => array( 'simple_grid_field5',
'simple_grid_field29' ),
'ShipperAddress' => array( 'simple_grid_field6',
'simple_grid_field30' ),
'ConsigneeName' => array( 'simple_grid_field7',
'simple_grid_field31' ),
'ConsigneeAddress' => array( 'simple_grid_field8',
'simple_grid_field32' ),
'CarrierID' => array( 'simple_grid_field9',
'simple_grid_field33' ),
'Instructions' => array( 'simple_grid_field10',
'simple_grid_field34' ),
'RFQResponseDate' => array( 'simple_grid_field11',
'simple_grid_field35' ),
'Description' => array( 'simple_grid_field12',
'simple_grid_field36' ),
'CarrierCompanyID' => array( 'simple_grid_field13',
'simple_grid_field37' ),
'CarrierAddress' => array( 'simple_grid_field14',
'simple_grid_field38' ),
'CarrierPhone' => array( 'simple_grid_field15',
'simple_grid_field39' ),
'CarrierFax' => array( 'simple_grid_field16',
'simple_grid_field40' ),
'EquipmentType' => array( 'simple_grid_field17',
'simple_grid_field41' ),
'ContactDetails' => array( 'simple_grid_field18',
'simple_grid_field42' ),
'PickupDate' => array( 'simple_grid_field19',
'simple_grid_field43' ),
'DeliveryDate' => array( 'simple_grid_field20',
'simple_grid_field44' ),
'SalesRepName' => array( 'simple_grid_field21',
'simple_grid_field45' ),
'SalesRepEmail' => array( 'simple_grid_field22',
'simple_grid_field46' ),
'SalesRepPrimaryPhone' => array( 'simple_grid_field23',
'simple_grid_field47' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'inline_save_all',
'inline_cancel_all',
'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field24',
'simple_grid_field',
'simple_grid_field25',
'simple_grid_field1',
'simple_grid_field26',
'simple_grid_field2',
'simple_grid_field27',
'simple_grid_field3',
'simple_grid_field28',
'simple_grid_field4',
'simple_grid_field29',
'simple_grid_field5',
'simple_grid_field30',
'simple_grid_field6',
'simple_grid_field31',
'simple_grid_field7',
'simple_grid_field32',
'simple_grid_field8',
'simple_grid_field33',
'simple_grid_field9',
'simple_grid_field34',
'simple_grid_field10',
'simple_grid_field35',
'simple_grid_field11',
'simple_grid_field36',
'simple_grid_field12',
'simple_grid_field37',
'simple_grid_field13',
'simple_grid_field38',
'simple_grid_field14',
'simple_grid_field39',
'simple_grid_field15',
'simple_grid_field40',
'simple_grid_field16',
'simple_grid_field41',
'simple_grid_field17',
'simple_grid_field42',
'simple_grid_field18',
'simple_grid_field43',
'simple_grid_field19',
'simple_grid_field44',
'simple_grid_field20',
'simple_grid_field45',
'simple_grid_field21',
'simple_grid_field46',
'simple_grid_field22',
'simple_grid_field47',
'simple_grid_field23',
'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'saveall_link',
'cancelall_link',
'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'inline_save_all' => 'above-grid',
'inline_cancel_all' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'simple_grid_field24' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field23' => 'grid',
'grid_inline_edit' => 'grid',
'grid_inline_save' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'grid_inline_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'expand_menu_button' => 2,
'breadcrumb' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'-' => array( '-',
'-1',
'-2',
'-3' ),
'advsearch_link' => array( 'advsearch_link' ),
'edit_selected' => array( 'edit_selected' ),
'inline_save_all' => array( 'inline_save_all' ),
'inline_cancel_all' => array( 'inline_cancel_all' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23' ),
'grid_field_label' => array( 'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47' ),
'grid_inline_edit' => array( 'grid_inline_edit' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'ID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'CustomerID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'EffectiveDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'ExpiryDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'IssueDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperName_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeName_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'CarrierID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'Instructions_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'RFQResponseDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'Description_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'CarrierCompanyID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'CarrierAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'CarrierPhone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'CarrierFax_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'EquipmentType_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'ContactDetails_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'PickupDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'DeliveryDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'SalesRepName_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'SalesRepEmail_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'SalesRepPrimaryPhone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inlineedit_column',
'inline_save',
'inline_cancel' ),
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'ID_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'CustomerID_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'EffectiveDate_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'ExpiryDate_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'IssueDate_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperName_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeName_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'CarrierID_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'Instructions_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'RFQResponseDate_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'Description_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'CarrierCompanyID_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'CarrierAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'CarrierPhone_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'CarrierFax_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'EquipmentType_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'ContactDetails_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'PickupDate_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'DeliveryDate_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'SalesRepName_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'SalesRepEmail_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'SalesRepPrimaryPhone_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 26,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_save_all',
'inline_cancel_all' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'ID',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'ID',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'CustomerID',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'CustomerID',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'EffectiveDate',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'EffectiveDate',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'ExpiryDate',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'ExpiryDate',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'IssueDate',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'IssueDate',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'ShipperName',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'ShipperName',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'ShipperAddress',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'ShipperAddress',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'ConsigneeName',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'ConsigneeName',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'ConsigneeAddress',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'ConsigneeAddress',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'CarrierID',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'CarrierID',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'Instructions',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'Instructions',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'RFQResponseDate',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'RFQResponseDate',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'Description',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'Description',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'CarrierCompanyID',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'CarrierCompanyID',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'CarrierAddress',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'CarrierAddress',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'CarrierPhone',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'CarrierPhone',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'CarrierFax',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'CarrierFax',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'EquipmentType',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'EquipmentType',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'ContactDetails',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'ContactDetails',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'PickupDate',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'PickupDate',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'DeliveryDate',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'DeliveryDate',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'SalesRepName',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'SalesRepName',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'SalesRepEmail',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'SalesRepEmail',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'SalesRepPrimaryPhone',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'SalesRepPrimaryPhone',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_edit',
'grid_inline_save',
'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field23',
'search_panel_field22',
'search_panel_field18',
'search_panel_field17',
'search_panel_field11',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'edit_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'CarrierAddress',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'CarrierCompanyID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'CarrierFax',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'CarrierID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'CarrierPhone',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field5' => array( 'field' => 'ConsigneeAddress',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field6' => array( 'field' => 'ConsigneeName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'ContactDetails',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field8' => array( 'field' => 'CustomerID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'Description',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'EffectiveDate',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field11' => array( 'field' => 'PickupDate',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'EquipmentType',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'ExpiryDate',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field14' => array( 'field' => 'ID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'Instructions',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'IssueDate',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field17' => array( 'field' => 'DeliveryDate',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'SalesRepName',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field19' => array( 'field' => 'RFQResponseDate',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field20' => array( 'field' => 'ShipperAddress',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field21' => array( 'field' => 'ShipperName',
'type' => 'search_panel_field',
'required' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-2' => array( 'type' => '-' ),
'edit_selected' => array( 'type' => 'edit_selected' ),
'-3' => array( 'type' => '-' ),
'inline_save_all' => array( 'type' => 'inline_save_all' ),
'inline_cancel_all' => array( 'type' => 'inline_cancel_all' ),
'search_panel_field22' => array( 'field' => 'SalesRepEmail',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'SalesRepPrimaryPhone',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field' => array( 'field' => 'ID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'ID' ),
'simple_grid_field1' => array( 'field' => 'CustomerID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'CustomerID' ),
'simple_grid_field2' => array( 'field' => 'EffectiveDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'EffectiveDate' ),
'simple_grid_field3' => array( 'field' => 'ExpiryDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'ExpiryDate' ),
'simple_grid_field4' => array( 'field' => 'IssueDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'IssueDate' ),
'simple_grid_field5' => array( 'field' => 'ShipperName',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'ShipperName' ),
'simple_grid_field6' => array( 'field' => 'ShipperAddress',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'ShipperAddress' ),
'simple_grid_field7' => array( 'field' => 'ConsigneeName',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeName' ),
'simple_grid_field8' => array( 'field' => 'ConsigneeAddress',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeAddress' ),
'simple_grid_field9' => array( 'field' => 'CarrierID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'CarrierID' ),
'simple_grid_field10' => array( 'field' => 'Instructions',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'Instructions' ),
'simple_grid_field11' => array( 'field' => 'RFQResponseDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'RFQResponseDate' ),
'simple_grid_field12' => array( 'field' => 'Description',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'Description' ),
'simple_grid_field13' => array( 'field' => 'CarrierCompanyID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'CarrierCompanyID' ),
'simple_grid_field14' => array( 'field' => 'CarrierAddress',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'CarrierAddress' ),
'simple_grid_field15' => array( 'field' => 'CarrierPhone',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'CarrierPhone' ),
'simple_grid_field16' => array( 'field' => 'CarrierFax',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'CarrierFax' ),
'simple_grid_field17' => array( 'field' => 'EquipmentType',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'EquipmentType' ),
'simple_grid_field18' => array( 'field' => 'ContactDetails',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => true ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'ContactDetails' ),
'simple_grid_field19' => array( 'field' => 'PickupDate',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'PickupDate' ),
'simple_grid_field20' => array( 'field' => 'DeliveryDate',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'DeliveryDate' ),
'simple_grid_field21' => array( 'field' => 'SalesRepName',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'SalesRepName' ),
'simple_grid_field22' => array( 'field' => 'SalesRepEmail',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'SalesRepEmail' ),
'simple_grid_field23' => array( 'field' => 'SalesRepPrimaryPhone',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'SalesRepPrimaryPhone' ),
'grid_inline_edit' => array( 'type' => 'grid_inline_edit' ),
'grid_inline_save' => array( 'type' => 'grid_inline_save' ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 7 );
		?>