<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ID',
'companyID',
'Routing',
'Instructions',
'RFQStatusID',
'RFQResponseDate',
'ShipperInstructions',
'ConsigneeInstructions',
'ShipperAddress',
'ConsigneeAddress' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'simple_grid_field',
'simple_grid_field3' ),
'companyID' => array( 'simple_grid_field1',
'simple_grid_field6' ),
'Routing' => array( 'simple_grid_field61',
'simple_grid_field63' ),
'Instructions' => array( 'simple_grid_field62',
'simple_grid_field64' ),
'RFQStatusID' => array( 'simple_grid_field2',
'simple_grid_field7' ),
'RFQResponseDate' => array( 'simple_grid_field56',
'simple_grid_field57' ),
'ShipperInstructions' => array( 'simple_grid_field4',
'simple_grid_field8' ),
'ConsigneeInstructions' => array( 'simple_grid_field5',
'simple_grid_field9' ),
'ShipperAddress' => array( 'simple_grid_field48',
'simple_grid_field50' ),
'ConsigneeAddress' => array( 'simple_grid_field49',
'simple_grid_field51' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'inline_add' ),
'below-grid' => array(  ),
'top' => array( 'back_master',
'masterlist_header' ),
'grid' => array( 'simple_grid_field3',
'simple_grid_field',
'simple_grid_field6',
'simple_grid_field1',
'simple_grid_field63',
'simple_grid_field61',
'simple_grid_field64',
'simple_grid_field62',
'simple_grid_field7',
'simple_grid_field2',
'simple_grid_field57',
'simple_grid_field56',
'simple_grid_field8',
'simple_grid_field4',
'simple_grid_field9',
'simple_grid_field5',
'simple_grid_field50',
'simple_grid_field48',
'simple_grid_field51',
'simple_grid_field49',
'grid_inline_cancel' ) ),
'formXtTags' => array( 'above-grid' => array( 'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'inline_add' => 'above-grid',
'back_master' => 'top',
'masterlist_header' => 'top',
'simple_grid_field3' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field49' => 'grid',
'grid_inline_cancel' => 'grid' ),
'itemLocations' => array( 'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterlist_header' => array( 'masterlist_header' ),
'back_master' => array( 'back_master' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field2',
'simple_grid_field56',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field48',
'simple_grid_field49' ),
'grid_field_label' => array( 'simple_grid_field3',
'simple_grid_field6',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field7',
'simple_grid_field57',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field50',
'simple_grid_field51' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'ID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'companyID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Routing_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Instructions_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'RFQStatusID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'RFQResponseDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperInstructions_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeInstructions_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'ShipperAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'ConsigneeAddress_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inline_cancel' ),
'items' => array( 'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'ID_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'companyID_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Routing_fieldcolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Instructions_fieldcolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'RFQStatusID_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'RFQResponseDate_fieldcolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperInstructions_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeInstructions_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'ShipperAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'ConsigneeAddress_fieldcolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 11,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'masterlist',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterlist',
'type' => 'masterlist',
'layoutId' => 'masterlist',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'back_master',
'masterlist_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'ID',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'ID',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'companyID',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'companyID',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'Routing',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'Routing',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'Instructions',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'Instructions',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'RFQStatusID',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'RFQStatusID',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'RFQResponseDate',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'RFQResponseDate',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'ShipperInstructions',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'ShipperInstructions',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'ConsigneeInstructions',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'ConsigneeInstructions',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'ShipperAddress',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'ShipperAddress',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'ConsigneeAddress',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'ConsigneeAddress',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterlist_header' => array( 'type' => 'masterlist_header' ),
'back_master' => array( 'type' => 'back_master' ),
'simple_grid_field' => array( 'field' => 'ID',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'type' => 'grid_field_label',
'field' => 'ID' ),
'simple_grid_field1' => array( 'field' => 'companyID',
'type' => 'grid_field' ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'companyID' ),
'simple_grid_field61' => array( 'field' => 'Routing',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'Routing' ),
'simple_grid_field62' => array( 'field' => 'Instructions',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'Instructions' ),
'simple_grid_field2' => array( 'field' => 'RFQStatusID',
'type' => 'grid_field' ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'RFQStatusID' ),
'simple_grid_field56' => array( 'field' => 'RFQResponseDate',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'RFQResponseDate' ),
'simple_grid_field4' => array( 'field' => 'ShipperInstructions',
'type' => 'grid_field' ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'ShipperInstructions' ),
'simple_grid_field5' => array( 'field' => 'ConsigneeInstructions',
'type' => 'grid_field' ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeInstructions' ),
'simple_grid_field48' => array( 'field' => 'ShipperAddress',
'type' => 'grid_field' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'ShipperAddress' ),
'simple_grid_field49' => array( 'field' => 'ConsigneeAddress',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeAddress' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 7 );
		?>