<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'master' => array( 'tbl_rfq_carrier_quote' => array( 'preview' => false ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => false,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'ID' => array( 'totalsType' => '' ),
'companyID' => array( 'totalsType' => '' ),
'RFQStatusID' => array( 'totalsType' => '' ),
'ShipperAddress' => array( 'totalsType' => '' ),
'ShipperInstructions' => array( 'totalsType' => '' ),
'ShipperDirections' => array( 'totalsType' => '' ),
'ConsigneeAddress' => array( 'totalsType' => '' ),
'ConsigneeInstructions' => array( 'totalsType' => '' ),
'ConsigneeDirections' => array( 'totalsType' => '' ),
'RFQResponseDate' => array( 'totalsType' => '' ),
'Instructions' => array( 'totalsType' => '' ),
'Routing' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'RFQStatusID',
'RFQResponseDate',
'ShipperAddress',
'ShipperInstructions',
'ShipperDirections',
'ConsigneeAddress',
'ConsigneeInstructions',
'ConsigneeDirections',
'Instructions',
'Routing' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'RFQStatusID' => array( 'simple_grid_field',
'simple_grid_field1' ),
'RFQResponseDate' => array( 'simple_grid_field8',
'simple_grid_field9' ),
'ShipperAddress' => array( 'grid_field',
'grid_field8' ),
'ShipperInstructions' => array( 'grid_field1',
'grid_field9' ),
'ShipperDirections' => array( 'grid_field2',
'grid_field10' ),
'ConsigneeAddress' => array( 'grid_field3',
'grid_field11' ),
'ConsigneeInstructions' => array( 'grid_field4',
'grid_field12' ),
'ConsigneeDirections' => array( 'grid_field5',
'grid_field13' ),
'Instructions' => array( 'grid_field6',
'grid_field14' ),
'Routing' => array( 'grid_field7',
'grid_field15' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'inline_add',
'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'top' => array(  ),
'grid' => array( 'grid_inline_cancel',
'simple_grid_field1',
'simple_grid_field',
'simple_grid_field9',
'simple_grid_field8',
'grid_field8',
'grid_field',
'grid_field9',
'grid_field1',
'grid_field10',
'grid_field2',
'grid_field11',
'grid_field3',
'grid_field12',
'grid_field4',
'grid_field13',
'grid_field5',
'grid_field14',
'grid_field6',
'grid_field15',
'grid_field7' ) ),
'formXtTags' => array( 'above-grid' => array( 'inlineadd_link',
'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'inline_add' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'grid_inline_cancel' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field8' => 'grid',
'grid_field8' => 'grid',
'grid_field' => 'grid',
'grid_field9' => 'grid',
'grid_field1' => 'grid',
'grid_field10' => 'grid',
'grid_field2' => 'grid',
'grid_field11' => 'grid',
'grid_field3' => 'grid',
'grid_field12' => 'grid',
'grid_field4' => 'grid',
'grid_field13' => 'grid',
'grid_field5' => 'grid',
'grid_field14' => 'grid',
'grid_field6' => 'grid',
'grid_field15' => 'grid',
'grid_field7' => 'grid' ),
'itemLocations' => array( 'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'expand_menu_button' => 2,
'breadcrumb' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field8',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4',
'grid_field5',
'grid_field6',
'grid_field7' ),
'grid_field_label' => array( 'simple_grid_field1',
'simple_grid_field9',
'grid_field8',
'grid_field9',
'grid_field10',
'grid_field11',
'grid_field12',
'grid_field13',
'grid_field14',
'grid_field15' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array( 'inline_cancel' ),
'items' => array( 'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'RFQStatusID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'RFQStatusID_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'RFQResponseDate_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'RFQResponseDate_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'ShipperAddress_fieldheadercolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'ShipperAddress_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'ShipperInstructions_fieldheadercolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'ShipperInstructions_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'ShipperDirections_fieldheadercolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'ShipperDirections_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'ConsigneeAddress_fieldheadercolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array( 'ConsigneeAddress_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'ConsigneeInstructions_fieldheadercolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'ConsigneeInstructions_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'ConsigneeDirections_fieldheadercolumn' ),
'items' => array( 'grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array( 'ConsigneeDirections_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'Instructions_fieldheadercolumn' ),
'items' => array( 'grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array( 'Instructions_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'Routing_fieldheadercolumn' ),
'items' => array( 'grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array( 'Routing_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 12 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 1,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'vertical-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 2 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 2 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'grid_inline_cancel' ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field1' ),
'field' => 'RFQStatusID',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'RFQStatusID',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field9' ),
'field' => 'RFQResponseDate',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'RFQResponseDate',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'grid_field8' ),
'field' => 'ShipperAddress',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'ShipperAddress',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'grid_field9' ),
'field' => 'ShipperInstructions',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'ShipperInstructions',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'grid_field10' ),
'field' => 'ShipperDirections',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'ShipperDirections',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'grid_field11' ),
'field' => 'ConsigneeAddress',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'ConsigneeAddress',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'grid_field12' ),
'field' => 'ConsigneeInstructions',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'ConsigneeInstructions',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'grid_field13' ),
'field' => 'ConsigneeDirections',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'ConsigneeDirections',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'grid_field14' ),
'field' => 'Instructions',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'Instructions',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'grid_field15' ),
'field' => 'Routing',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'Routing',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link' ) ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'simple_grid_field' => array( 'field' => 'RFQStatusID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field1' => array( 'type' => 'grid_field_label',
'field' => 'RFQStatusID',
'clickSort' => true ),
'simple_grid_field8' => array( 'field' => 'RFQResponseDate',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'RFQResponseDate',
'clickSort' => true ),
'grid_field' => array( 'field' => 'ShipperAddress',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'ShipperAddress' ),
'grid_field1' => array( 'field' => 'ShipperInstructions',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'ShipperInstructions' ),
'grid_field2' => array( 'field' => 'ShipperDirections',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'ShipperDirections' ),
'grid_field3' => array( 'field' => 'ConsigneeAddress',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeAddress' ),
'grid_field4' => array( 'field' => 'ConsigneeInstructions',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeInstructions' ),
'grid_field5' => array( 'field' => 'ConsigneeDirections',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'ConsigneeDirections' ),
'grid_field6' => array( 'field' => 'Instructions',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'Instructions' ),
'grid_field7' => array( 'field' => 'Routing',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'Routing' ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 7,
'reorderRows' => false,
'reorderRowsField' => '' );
		?>