<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_formfields1  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;


		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		/*if($_SESSION["formid"]){
	$selectsqlfields = "<option value=''>Please select...</option>";
	$rs = DB::Query("select * from sqlfields where formid=".$_SESSION["formid"]);
	while($mdata = $rs->fetchAssoc()){
		$s = "";
		$needAdd = true;
		if($data["fieldsql"] == $mdata["sqlfield"])
			$s = " selected";
		else{
			$rs2 = DB::Query("select count(id) as cnt from formfields where fieldsql='".$mdata["sqlfield"]."' and formid=".$_SESSION["formid"]);
			$data2 = $rs2->fetchAssoc();
			if($data2["cnt"]>0)
				$needAdd = false;
		}
		if($needAdd)
			$selectsqlfields.= "<option value='".$mdata["sqlfield"]."'".$s.">".$mdata["sqlfield"]."</option>";
	}
	$record["id_value"] = "<select class='form-control' id='sqlfield_".$data["id"]."' fieldid='".$data["id"]."'>".$selectsqlfields."</select>";
}*/
if($data["fieldsql"])
	$record["id_value"] = "<select class='form-control' id='sqlfield_".$data["id"]."' fieldid='".$data["id"]."'><option value='".$data["fieldsql"]."'>".$data["fieldsql"]."</option></select>";
else
	$record["id_value"] = "<select class='form-control' id='sqlfield_".$data["id"]."' fieldid='".$data["id"]."'><option value=''>Please select...</option></select>";


;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList($pageObject)
{

		if(postvalue("a") == "savesqlfield"){
	DB::Exec("update formfields set fieldsql='".postvalue("val")."' where id=".postvalue("fieldid"));
	exit();
}
if(postvalue("a") == "getselect"){
	$rs = DB::Query("select * from formfields where id=".postvalue("fieldid"));
	$data = $rs->fetchAssoc();
	$formid = $data["formid"];

	$multif = postvalue("multifields");

	$selectsqlfields = "<option value=''>Please select...</option>";
	$rs = DB::Query("select * from sqlfields where formid=".$formid);
	while($mdata = $rs->fetchAssoc()){
		$s = "";
		$needAdd = true;
		if($data["fieldsql"] == $mdata["sqlfield"])
			$s = " selected";
		else{
			if($multif!="true"){
				$rs2 = DB::Query("select count(id) as cnt from formfields where fieldsql='".$mdata["sqlfield"]."' and formid=".$formid);
				$data2 = $rs2->fetchAssoc();
				if($data2["cnt"]>0)
					$needAdd = false;
			}
		}
		if($needAdd)
			$selectsqlfields.= "<option value='".$mdata["sqlfield"]."'".$s.">".$mdata["sqlfield"]."</option>";
	}
	echo $selectsqlfields;
	exit();
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

return false;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
